// Generates the JSH calendar seed in supabase/migrations/0512_jsh_calendars.sql
// from the saved snapshot of JSH's public calendars (supabase/data/jsh-calendar,
// taken 2026-09-25 from https://www.jainsocietyhouston.org/jsheventcalendar).
//
// It runs the same parser and window as a calendar subscription
// (src/calendar/ics.ts, feedWindow of the snapshot date), so the seeded rows are
// exactly what subscribing each layer to its link would produce, and the
// seeded layers stay subscribed to those links so the daily refresh keeps them
// current. worker/test/jsh-calendar-seed.test.ts fails when the migration and
// this output differ; regenerate with
//   (cd worker && GEN_JSH_CALENDAR_SEED=1 pnpm exec vitest run test/jsh-calendar-seed.test.ts)

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { expandCalendar, feedWindow, parseIcs, type FeedEntry } from "../src/calendar/ics";

export const SNAPSHOT_DATE = "2026-09-25";
export const TIME_ZONE = "America/Chicago";
export const DATA_DIR = fileURLToPath(new URL("../../supabase/data/jsh-calendar/", import.meta.url));
export const MIGRATION = fileURLToPath(new URL("../../supabase/migrations/0512_jsh_calendars.sql", import.meta.url));
export const BEGIN = "-- BEGIN jsh calendar seed (generated by worker/scripts/jsh-calendar-seed.ts from supabase/data/jsh-calendar)";
export const END = "-- END jsh calendar seed";

const google = (id: string) => `https://calendar.google.com/calendar/ical/${id}%40group.calendar.google.com/public/basic.ics`;

export type SeedLayer = {
  file: string;
  /** Existing layer key reused when present (the JSH seed has "events" and "pathshala"). */
  key: string;
  kind: "tithi" | "festival" | "pathshala" | "events" | "school_district" | "custom";
  name: string;
  color: string;
  defaultOn: boolean;
  url: string;
  createsEvents: boolean;
};

export const LAYERS: SeedLayer[] = [
  { file: "jsh-events.ics", key: "events", kind: "events", name: "JSH Events", color: "#7A2E1F", defaultOn: true,
    url: google("c_b050cd4bd2d10bef85e59c50531e6db289c6c2c366391ee13c39505756b114d8"), createsEvents: true },
  { file: "jsh-pathshala.ics", key: "pathshala", kind: "pathshala", name: "JSH Pathshala", color: "#5B4B8A", defaultOn: true,
    url: google("c_8c7e320c0ec80b29d227f1bddf423f1e3604a798717d1f6d4d19c1359db81b67"), createsEvents: false },
  { file: "jain-panchang.ics", key: "jain_panchang", kind: "tithi", name: "Jain Panchang", color: "#C9731C", defaultOn: true,
    url: google("c_3aaaeb46603ba3aeb2acb38c894925059a7daaac2a77375b29b3c85922df8f35"), createsEvents: false },
  { file: "jsh-bhaktamber-online.ics", key: "bhaktamber_online", kind: "custom", name: "Bhaktamber sessions (online)", color: "#1B5E9C", defaultOn: false,
    url: google("c_4fb76d280c2b127e0172a25cdff00ec2335d5d7ed199342ba03e45b271c533f0"), createsEvents: false },
  { file: "jsh-shine-online.ics", key: "shine_online", kind: "custom", name: "SHINE online sessions", color: "#1F7A4D", defaultOn: false,
    url: google("c_7b8855ecffe2ae7cd81e17f1dcb8bf24f451df9df04f3932e8d1c9db118b5165"), createsEvents: false },
  { file: "fbisd.ics", key: "school_fbisd", kind: "school_district", name: "School calendar (FBISD)", color: "#9C1B5E", defaultOn: false,
    url: google("c_a1c6aff2fd914af1ae3787c8de9b17875892a908e12f989c0323aebb41369b2f"), createsEvents: false },
];

/** Clearly internal reminders on the public calendars, left out of the seed (UID → why). */
export const SKIP: Record<string, string> = {
  "0ejefe7h1nivesecctn833nulu@google.com": "an office reminder (\"Make sure tax exemption for the new location is extended\"), not a community event",
};

export type SeedLayerOutput = { layer: SeedLayer; calendarName: string | null; entries: FeedEntry[]; skipped: { uid: string; title: string; reason: string }[] };

export function jshCalendarEntries(): SeedLayerOutput[] {
  const window = feedWindow(SNAPSHOT_DATE);
  return LAYERS.map((layer) => {
    const cal = parseIcs(readFileSync(`${DATA_DIR}${layer.file}`, "utf8"));
    cal.events = cal.events.filter((e) => !SKIP[e.uid]);
    const { entries, skipped } = expandCalendar(cal, { displayZone: TIME_ZONE, window });
    return { layer, calendarName: cal.name, entries, skipped };
  });
}

const sqlText = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** The generated statements (between BEGIN and END in the migration). */
export function jshCalendarSeedSql(): string {
  const window = feedWindow(SNAPSHOT_DATE);
  const out: string[] = [];
  for (const { layer, calendarName, entries } of jshCalendarEntries()) {
    const json = `[\n${entries.map((e) => JSON.stringify(e)).join(",\n")}\n]`;
    if (json.includes("$json$")) throw new Error(`${layer.file}: an entry contains the SQL quote marker $json$`);
    const feed = JSON.stringify({ calendar_name: calendarName, snapshot: SNAPSHOT_DATE, window });
    out.push(
      `  -- ${calendarName ?? layer.file} (${layer.file}): ${entries.length} dates`,
      `  v_layer := app.calendar_seed_layer(p_center, ${sqlText(layer.key)}, ${sqlText(layer.kind)}, ${sqlText(layer.name)}, ${sqlText(layer.color)}, ${layer.defaultOn}, ${sqlText(layer.url)}, ${layer.createsEvents});`,
      `  v_out := v_out || jsonb_build_object(${sqlText(layer.key)}, app.calendar_seed_apply(v_layer, $json$${json}$json$::jsonb, date ${sqlText(window.recurFrom)}, ${sqlText(feed)}::jsonb));`,
    );
  }
  return out.join("\n");
}
