"use client";

import { useRouter } from "next/navigation";
import { useEffect, useId, useRef, useState, useTransition } from "react";

import { Modal } from "@/components/modal";
import { useStepUp } from "@/components/step-up";
import { useToast } from "@/components/toast";
import { buttonClass } from "@/components/ui";

import {
  completeStepAction, generateFieldAction, parkStepAction, reopenStepAction, saveFieldAction, setupLaterAction, testSignInHookAction, testStepAction,
  type SetupResult,
} from "./actions";

// The interactive parts of the platform setup wizard. Values typed here go to
// the server action once; nothing sent back to the browser ever contains a key
// (the reply carries its last 4 characters).

type Edit = {
  name: string;
  label: string;
  kind: "secret" | "setting";
  mode: "save" | "replace" | "generate";
  hint: string;
  placeholder: string | null;
  options: { value: string; label: string }[] | null;
  current: string | null;
};

function useRun() {
  const toast = useToast();
  const stepUp = useStepUp();
  const router = useRouter();
  return async function run<T>(fn: () => Promise<SetupResult<T>>, what: string): Promise<SetupResult<T>> {
    let res: SetupResult<T>;
    try {
      res = stepUp ? await stepUp.run(fn, what) : await fn();
    } catch (err) {
      console.error(`[platform-setup] ${what} failed:`, err);
      res = { ok: false, error: `Could not ${what} — the server did not answer. Check the connection and try again. Nothing was changed.` };
    }
    if (res.ok) {
      toast?.show(res.message ?? "Done", "ok");
      router.refresh();
    } else {
      toast?.show(res.error, "bad");
    }
    return res;
  };
}

/** Save / Replace / Generate for one field: value (never pre-filled for a key), reason, fresh 2FA check. */
export function FieldButton({ field, mode, label, kind = "ghost" }: { field: Omit<Edit, "mode">; mode: Edit["mode"]; label: string; kind?: "ghost" | "primary" }) {
  const run = useRun();
  const [open, setOpen] = useState(false);
  const [value, setValue] = useState("");
  const [reason, setReason] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [working, setWorking] = useState(false);
  const valueId = useId();
  const reasonId = useId();

  function show() {
    setValue(field.kind === "setting" ? (field.current ?? field.options?.[0]?.value ?? "") : "");
    setReason(mode === "generate" ? "Generated by the setup wizard" : field.current || mode === "replace" ? "" : "Initial platform setup");
    setError(null);
    setOpen(true);
  }

  async function confirm() {
    if (mode !== "generate" && !value.trim()) return setError(`Enter the ${field.label.toLowerCase()}.`);
    if (!reason.trim()) return setError("Say why — the reason is kept in the audit log.");
    setWorking(true);
    setError(null);
    setOpen(false); // the 2FA check may open on top
    const what = mode === "generate" ? `generate the ${field.label.toLowerCase()}` : `save the ${field.label.toLowerCase()}`;
    const res = await run(() => (mode === "generate" ? generateFieldAction(field.name, reason) : saveFieldAction(field.name, value, reason)), what);
    setWorking(false);
    if (res.ok) {
      setValue("");
      return;
    }
    setError(res.error);
    setOpen(true);
  }

  return (
    <>
      <button type="button" className={buttonClass(kind, "xs")} onClick={show} disabled={working} data-field={field.name} data-mode={mode}>
        {working ? "Saving…" : label}
      </button>
      <Modal
        open={open}
        kicker="Platform setup"
        title={mode === "generate" ? `Generate the ${field.label.toLowerCase()}` : `${mode === "replace" ? "Replace" : "Save"} the ${field.label.toLowerCase()}`}
        confirmLabel={mode === "generate" ? "Generate" : "Save"}
        pending={working}
        error={error}
        onConfirm={() => void confirm()}
        onCancel={() => {
          setOpen(false);
          setValue("");
        }}
      >
        {mode === "generate" ? (
          <p>The server makes a long random value and keeps it in the vault. Nobody sees it, and nobody needs to.{field.current ? " Anything signed with the old value stops working." : ""}</p>
        ) : (
          <>
            <p className="text-[13px] text-muted">{field.hint}</p>
            <label htmlFor={valueId} className="crm-label mt-3 block">
              {field.label}
            </label>
            {field.options ? (
              <select id={valueId} className="crm-input w-full" value={value} onChange={(e) => setValue(e.target.value)}>
                {field.options.map((o) => (
                  <option key={o.value} value={o.value}>
                    {o.label}
                  </option>
                ))}
              </select>
            ) : (
              <input
                id={valueId}
                name={field.kind === "secret" ? "secret-value" : "setting-value"}
                type={field.kind === "secret" ? "password" : "text"}
                className="crm-input w-full font-mono"
                value={value}
                placeholder={field.placeholder ?? undefined}
                onChange={(e) => setValue(e.target.value)}
                autoComplete="off"
                spellCheck={false}
              />
            )}
            {field.kind === "secret" ? (
              <p className="crm-hint">Kept encrypted in the vault. It is never shown again — only its last 4 characters. Changing it needs a fresh 2FA check.</p>
            ) : null}
          </>
        )}
        <label htmlFor={reasonId} className="crm-label mt-3 block">
          Reason (kept in the audit log)
        </label>
        <input id={reasonId} className="crm-input w-full" value={reason} onChange={(e) => setReason(e.target.value)} maxLength={500} />
      </Modal>
    </>
  );
}

/** Test with the background service, then keep refreshing until its result is in. */
export function TestButton({ step, busy }: { step: string; busy: boolean }) {
  const run = useRun();
  const [working, start] = useTransition();
  return (
    <>
      <button type="button" className={buttonClass("ghost", "sm")} disabled={working || busy} onClick={() => start(async () => void (await run(() => testStepAction(step), "start the test")))}>
        {busy ? "Testing…" : working ? "Queuing…" : "Test"}
      </button>
      <AutoRefresh active={busy} />
    </>
  );
}

/** Refresh the page every 2 s while something runs in the background (at most a minute). */
export function AutoRefresh({ active }: { active: boolean }) {
  const router = useRouter();
  const started = useRef<number | null>(null);
  useEffect(() => {
    if (!active) {
      started.current = null;
      return;
    }
    started.current ??= Date.now();
    const t = setInterval(() => {
      if (started.current && Date.now() - started.current > 60000) return clearInterval(t);
      router.refresh();
    }, 2000);
    return () => clearInterval(t);
  }, [active, router]);
  return null;
}

/** Sign-in hooks: send a sign-in code to yourself; the page then shows whether the hook carried it. */
export function HookTestButton() {
  const run = useRun();
  const [working, start] = useTransition();
  const [since, setSince] = useState<string | null>(null);
  return (
    <>
      <button
        type="button"
        className={buttonClass("ghost", "sm")}
        disabled={working}
        onClick={() =>
          start(async () => {
            const res = await run(() => testSignInHookAction(), "send a test sign-in code");
            if (res.ok && res.data) {
              setSince(res.data.since);
              setTimeout(() => setSince(null), 20000);
            }
          })
        }
      >
        {working ? "Sending…" : "Send me a test sign-in code"}
      </button>
      <AutoRefresh active={since !== null} />
    </>
  );
}

/** Mark done / Park for later / Reopen. */
export function StepActions({ step, title, required, status, canComplete, why }: { step: string; title: string; required: boolean; status: string; canComplete: boolean; why: string }) {
  const run = useRun();
  const [working, start] = useTransition();
  const [ask, setAsk] = useState<null | "park" | "reopen">(null);
  const [reason, setReason] = useState("");
  const [error, setError] = useState<string | null>(null);
  const reasonId = useId();

  async function confirm() {
    if (!reason.trim()) return setError(ask === "park" ? "Say why you are parking it — it shows on the reminder." : "Say why — the reason is kept in the audit log.");
    const kind = ask;
    setAsk(null);
    const res = await run(() => (kind === "park" ? parkStepAction(step, reason) : reopenStepAction(step, reason)), kind === "park" ? "park the step" : "reopen the step");
    if (!res.ok) {
      setError(res.error);
      setAsk(kind);
    } else setReason("");
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      {status !== "done" ? (
        <button
          type="button"
          className={buttonClass(canComplete ? "ok" : "off", "sm")}
          disabled={working || !canComplete}
          title={canComplete ? undefined : why}
          onClick={() => start(async () => void (await run(() => completeStepAction(step), "mark the step done")))}
        >
          {working ? "Checking…" : "Mark done"}
        </button>
      ) : null}
      {!required && status === "not_started" ? (
        <button type="button" className={buttonClass("ghost", "sm")} onClick={() => (setError(null), setReason(""), setAsk("park"))}>
          Park for later
        </button>
      ) : null}
      {status !== "not_started" ? (
        <button type="button" className={buttonClass("ghost", "sm")} onClick={() => (setError(null), setReason(""), setAsk("reopen"))}>
          {status === "parked" ? "Set up now" : "Reopen"}
        </button>
      ) : null}
      {required && status !== "done" ? <span className="text-[12px] font-semibold text-muted">Required — it cannot be parked.</span> : null}
      <Modal
        open={ask !== null}
        kicker="Platform setup"
        title={ask === "park" ? `Park "${title}" for later` : `${status === "parked" ? "Set up" : "Reopen"} "${title}"`}
        confirmLabel={ask === "park" ? "Park it" : "Reopen"}
        error={error}
        onConfirm={() => void confirm()}
        onCancel={() => setAsk(null)}
      >
        <p>
          {ask === "park"
            ? "The step stays on the Platform home as a reminder, with your name and the date. Come back to it any time."
            : "The step goes back to the list of things to do."}
        </p>
        <label htmlFor={reasonId} className="crm-label mt-3 block">
          Reason (kept in the audit log)
        </label>
        <input id={reasonId} className="crm-input w-full" value={reason} onChange={(e) => setReason(e.target.value)} maxLength={500} />
      </Modal>
    </div>
  );
}

/** "Continue to the portal": stop sending you here for this browser session. */
export function LaterButton() {
  const router = useRouter();
  const toast = useToast();
  const [working, start] = useTransition();
  return (
    <button
      type="button"
      className={buttonClass("ghost", "sm")}
      disabled={working}
      onClick={() =>
        start(async () => {
          try {
            const res = await setupLaterAction();
            if (!res.ok) return void toast?.show(res.error, "bad");
            router.push("/");
          } catch (err) {
            console.error("[platform-setup] setupLaterAction failed:", err);
            toast?.show("Could not continue — the server did not answer. Try again.", "bad");
          }
        })
      }
    >
      Continue to the portal for now
    </button>
  );
}
