// Event flyers — the flyer maker's pure parts (no server imports: the flyer
// panel is a client component and imports this file).
//
// A flyer is DESIGNED from the brand kit (owner decisions 2026-10-01): a
// template, a size, the words (headline, tagline, date line, venue line), an
// RSVP QR code, and one background — a pattern drawn in code, a photo from the
// community's approved albums, free AI background art, or a plain colour. The
// design is stored on the event as events.flyer_design (v1, migration 0578)
// and rendered server-side to a PNG (src/lib/events/flyer-render.tsx).
//
// AI art is art only: no text, letters, deities, idols or murtis, and no
// people up close. FLYER_ART_BLOCKED_TERMS and the two guardrails below are an
// exact copy of worker/src/flyer-guard.ts (tests/events-flyer.test.ts keeps
// them equal), so the portal refuses what the worker would refuse, before asking.
//
// Flyers v2 (owner decision 2026-10-02, approach C) adds the POSTER template:
// our layout and every word set by code (src/lib/events/flyer-poster.tsx) over
// an occasion art pack — a frame and a bottom scene drawn in code, or cached
// text-free AI art (src/lib/events/flyer-art.ts). Its content is stored in the
// same events.flyer_design, as `poster` (still v1: the field is optional, so
// every design saved before stays valid).

import { FLYER_ART_SEED_MAX, FLYER_LAYER_KINDS, isCenterArtPath, isFlyerOccasion, occasionFor, parseFlyerArtPath, type FlyerLayer, type FlyerLayerKind, type FlyerOccasion } from "./flyer-art";
import { isPosterIcon, type PosterIcon } from "./flyer-icons";
import { formatEventRange, formatTime } from "./format";

// ── Sources, templates, sizes, backgrounds ──────────────────────────────────

export type FlyerSource = "manual" | "ai" | "designed";

/** The events.flyer_source column, read defensively (it is a plain `text` column at the DB). */
export function readFlyerSource(v: string | null): FlyerSource | null {
  return v === "manual" || v === "ai" || v === "designed" ? v : null;
}

export const FLYER_SOURCE_LABEL: Record<FlyerSource, string> = {
  designed: "Made with the flyer maker",
  manual: "Uploaded",
  ai: "Generated by AI (earlier flyer)",
};

export type FlyerTemplate = "classic" | "festival" | "minimal" | "photo" | "poster";
export const FLYER_TEMPLATES: readonly FlyerTemplate[] = ["classic", "festival", "minimal", "photo", "poster"];
export const FLYER_TEMPLATE_LABEL: Record<FlyerTemplate, string> = {
  classic: "Classic",
  festival: "Festival",
  minimal: "Minimal",
  photo: "Photo",
  poster: "Poster",
};

export type FlyerSize = "post" | "tall" | "story" | "print";
/**
 * Print is US Letter at 300 dpi: twice the 1275 × 1650 layout, so the PDF is
 * sharp (the drawn art is vector and scales with it).
 */
export const FLYER_SIZES = {
  post: { w: 1080, h: 1350, label: "Post 1080×1350" },
  tall: { w: 1080, h: 1620, label: "Tall 1080×1620" },
  story: { w: 1080, h: 1920, label: "Story 1080×1920" },
  print: { w: 2550, h: 3300, label: "Print — US Letter (PDF)" },
} as const satisfies Record<FlyerSize, { w: number; h: number; label: string }>;
export const FLYER_SIZE_KEYS: readonly FlyerSize[] = ["post", "tall", "story", "print"];

export type FlyerPattern = "lotus" | "rangoli" | "diya" | "mandala";
export const FLYER_PATTERNS: readonly FlyerPattern[] = ["lotus", "rangoli", "diya", "mandala"];
export const FLYER_PATTERN_LABEL: Record<FlyerPattern, string> = { lotus: "Lotus", rangoli: "Rangoli", diya: "Diya", mandala: "Mandala" };

export type FlyerBackground =
  | { source: "pattern"; pattern: FlyerPattern }
  | { source: "photo"; photo_id: string }
  | { source: "ai"; path: string; prompt: string }
  | { source: "plain" };

// ── The Poster's content (flyer_design.poster, 0585) ─────────────────────────

export type PosterAgendaRow = { icon: PosterIcon; time: string; text: string };

/**
 * Everything the Poster template draws besides the headline (design.headline),
 * the venue (design.venue_line) and the QR code (design.show_qr). Every
 * section is optional: an empty or switched-off section is left out and the
 * rest of the poster closes up.
 */
export type PosterContent = {
  occasion: FlyerOccasion;
  frame: FlyerLayer;
  scene: FlyerLayer;
  /** The community's logo (brand kit) at the top. */
  logo: boolean;
  /** A partner's logo beside it: an uploaded PNG/JPEG, or a badge drawn from two short lines. */
  partner: { on: boolean; label: string; sub: string; logo_path: string | null };
  subhead: string;
  slogan: string;
  stat: { on: boolean; icon: PosterIcon; label: string; value: string; caption: string };
  /** The date ribbon: date and time lines (from the event by default) and the venue line. */
  ribbon: { on: boolean; date: string; time: string };
  /** 0 to 5 rows; none leaves the agenda out. */
  agenda: PosterAgendaRow[];
  paragraph: string;
  /** The footer band's line; empty shows the community's name. */
  footer: string;
};

export const POSTER_LIMITS = {
  subhead: 48,
  slogan: 60,
  // The badge is a disc about 90 units across inside: a longer line is set smaller to fit, and these are about the smallest it stays readable at.
  partner_label: 10,
  partner_sub: 8,
  stat_label: 24,
  stat_value: 10,
  stat_caption: 80,
  ribbon_date: 44,
  ribbon_time: 36,
  agenda_time: 22,
  agenda_text: 80,
  paragraph: 320,
  footer: 60,
} as const;
export const POSTER_AGENDA_MAX = 5;

const POSTER_FIELD_LABEL: Record<keyof typeof POSTER_LIMITS, string> = {
  subhead: "subhead",
  slogan: "slogan line",
  partner_label: "partner badge's first line",
  partner_sub: "partner badge's second line",
  stat_label: "highlight's small label",
  stat_value: "highlight's big number",
  stat_caption: "highlight's caption",
  ribbon_date: "ribbon's date",
  ribbon_time: "ribbon's time",
  agenda_time: "agenda time",
  agenda_text: "agenda line",
  paragraph: "paragraph",
  footer: "footer line",
};

/** events.flyer_design, v1 (contract C2, migration 0578; `poster` added by 0585). */
export type FlyerDesign = {
  v: 1;
  template: FlyerTemplate;
  size: FlyerSize;
  headline: string;
  tagline: string;
  date_line: string;
  venue_line: string;
  show_qr: boolean;
  background: FlyerBackground;
  /** The Poster template's content; kept while another template is chosen, so switching back loses nothing. */
  poster?: PosterContent;
};

export const FLYER_LIMITS = { headline: 90, tagline: 180, date_line: 90, venue_line: 120 } as const;
const FIELD_LABEL: Record<keyof typeof FLYER_LIMITS, string> = {
  headline: "headline",
  tagline: "tagline",
  date_line: "date line",
  venue_line: "venue line",
};

/** Characters as a person counts them (code points, so a Gujarati letter with its sign counts per symbol, not per UTF-16 unit). */
export function flyerTextLength(s: string): number {
  return Array.from(s).length;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ART_PATH = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/events\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/art-\d{1,16}\.(?:jpg|png)$/i;

/** Is this the storage key of THIS event's AI background art (content/<center>/events/<event>/art-<ms>.<jpg|png>)? */
export function isFlyerArtPath(path: string, centerId: string, eventId: string): boolean {
  return ART_PATH.test(path) && path.toLowerCase().startsWith(`${centerId}/events/${eventId}/art-`.toLowerCase());
}

function cleanLine(v: unknown): string {
  // Control characters (tabs, line breaks) and no-break spaces (a time such as "5:00 PM" may carry one) become
  // spaces: the flyer lays out its own lines, and a font may not have the glyph.
  return typeof v === "string" ? v.replace(/[\u0000-\u001F\u007F\u00A0\u202F]+/g, " ").replace(/ {2,}/g, " ").trim() : "";
}

const PARTNER_LOGO = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/events\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/partner-\d{1,16}\.(?:jpg|png)$/i;

/** Is this the storage key of THIS event's partner logo (content/<center>/events/<event>/partner-<ms>.<jpg|png>)? */
export function isPartnerLogoPath(path: string, centerId: string, eventId: string): boolean {
  return PARTNER_LOGO.test(path) && path.toLowerCase().startsWith(`${centerId}/events/${eventId}/partner-`.toLowerCase());
}

function parseLayer(raw: unknown, kind: "frame" | "scene", occasion: FlyerOccasion): { ok: true; value: FlyerLayer } | { ok: false; error: string } {
  const o = raw && typeof raw === "object" && !Array.isArray(raw) ? (raw as Record<string, unknown>) : null;
  const what = kind === "frame" ? "frame" : "bottom scene";
  if (!o || o.source === "code") return { ok: true, value: { source: "code" } };
  if (o.source === "none") return { ok: true, value: { source: "none" } };
  if (o.source === "ai") {
    const path = typeof o.path === "string" ? o.path.trim() : "";
    const parsed = parseFlyerArtPath(path);
    if (!parsed || parsed.layer !== kind) return { ok: false, error: `The AI ${what} is not one the flyer maker made. Choose it again, or use the drawn ${what}.` };
    if (parsed.occasion !== occasion) return { ok: false, error: `The AI ${what} was made for another occasion. Choose one made for this occasion, or use the drawn ${what}.` };
    return { ok: true, value: { source: "ai", path } };
  }
  return { ok: false, error: `Choose a ${what}: the drawn one, AI art, or none.` };
}

/** The Poster's content, checked; every error is a plain sentence for the organizer. */
export function parsePosterContent(raw: unknown): { ok: true; poster: PosterContent } | { ok: false; error: string } {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return { ok: false, error: "The poster's content is missing. Reload the page and try again." };
  const o = raw as Record<string, unknown>;
  const obj = (v: unknown) => (v && typeof v === "object" && !Array.isArray(v) ? (v as Record<string, unknown>) : {});
  if (!isFlyerOccasion(o.occasion)) return { ok: false, error: "Choose an occasion for the poster's art." };
  const occasion = o.occasion;
  const frame = parseLayer(o.frame, "frame", occasion);
  if (!frame.ok) return frame;
  const scene = parseLayer(o.scene, "scene", occasion);
  if (!scene.ok) return scene;
  const partner = obj(o.partner);
  const stat = obj(o.stat);
  const ribbon = obj(o.ribbon);
  const logoPath = typeof partner.logo_path === "string" && partner.logo_path.trim() ? partner.logo_path.trim() : null;
  if (logoPath && !PARTNER_LOGO.test(logoPath)) return { ok: false, error: "The partner logo is not one uploaded here. Upload it again." };
  const rawRows = Array.isArray(o.agenda) ? o.agenda : [];
  if (rawRows.length > POSTER_AGENDA_MAX) return { ok: false, error: `The agenda has room for ${POSTER_AGENDA_MAX} rows.` };
  const agenda: PosterAgendaRow[] = [];
  for (const r of rawRows) {
    const row = obj(r);
    const time = cleanLine(row.time);
    const text = cleanLine(row.text);
    if (!time && !text) continue;
    agenda.push({ icon: isPosterIcon(row.icon) ? row.icon : "clock", time, text });
  }
  const poster: PosterContent = {
    occasion,
    frame: frame.value,
    scene: scene.value,
    logo: o.logo !== false,
    partner: { on: partner.on === true, label: cleanLine(partner.label), sub: cleanLine(partner.sub), logo_path: logoPath },
    subhead: cleanLine(o.subhead),
    slogan: cleanLine(o.slogan),
    stat: {
      on: stat.on === true,
      icon: isPosterIcon(stat.icon) ? stat.icon : "people",
      label: cleanLine(stat.label),
      value: cleanLine(stat.value),
      caption: cleanLine(stat.caption),
    },
    ribbon: { on: ribbon.on !== false, date: cleanLine(ribbon.date), time: cleanLine(ribbon.time) },
    agenda,
    paragraph: cleanLine(o.paragraph),
    footer: cleanLine(o.footer),
  };
  const checks: [keyof typeof POSTER_LIMITS, string][] = [
    ["subhead", poster.subhead],
    ["slogan", poster.slogan],
    ["partner_label", poster.partner.label],
    ["partner_sub", poster.partner.sub],
    ["stat_label", poster.stat.label],
    ["stat_value", poster.stat.value],
    ["stat_caption", poster.stat.caption],
    ["ribbon_date", poster.ribbon.date],
    ["ribbon_time", poster.ribbon.time],
    ["paragraph", poster.paragraph],
    ["footer", poster.footer],
    ...poster.agenda.flatMap((r): [keyof typeof POSTER_LIMITS, string][] => [
      ["agenda_time", r.time],
      ["agenda_text", r.text],
    ]),
  ];
  for (const [key, value] of checks) {
    if (flyerTextLength(value) > POSTER_LIMITS[key]) return { ok: false, error: `The ${POSTER_FIELD_LABEL[key]} is longer than ${POSTER_LIMITS[key]} characters.` };
  }
  if (poster.stat.on && !poster.stat.value) return { ok: false, error: "The highlight needs its big number (or switch the highlight off)." };
  return { ok: true, poster };
}

/** Every AI layer the poster uses belongs to this community (checked again on the server before it is drawn). */
export function posterLayersBelongTo(poster: PosterContent, centerId: string): boolean {
  return FLYER_LAYER_KINDS.every((k) => {
    const l = poster[k];
    return l.source !== "ai" || isCenterArtPath(l.path, centerId, poster.occasion, k);
  });
}

function parseBackground(raw: unknown): { ok: true; value: FlyerBackground } | { ok: false; error: string } {
  const o = raw && typeof raw === "object" && !Array.isArray(raw) ? (raw as Record<string, unknown>) : null;
  const source = o?.source;
  if (source === "pattern") {
    const p = o?.pattern;
    if (typeof p === "string" && (FLYER_PATTERNS as readonly string[]).includes(p)) return { ok: true, value: { source, pattern: p as FlyerPattern } };
    return { ok: false, error: "Choose one of the patterns: lotus, rangoli, diya or mandala." };
  }
  if (source === "photo") {
    const id = o?.photo_id;
    if (typeof id === "string" && UUID.test(id)) return { ok: true, value: { source, photo_id: id.toLowerCase() } };
    return { ok: false, error: "Choose a photo from one of the albums." };
  }
  if (source === "ai") {
    const path = typeof o?.path === "string" ? o.path.trim() : "";
    if (!ART_PATH.test(path)) return { ok: false, error: "Generate the AI art first, or choose another background." };
    const prompt = typeof o?.prompt === "string" ? o.prompt.trim().slice(0, 2000) : "";
    return { ok: true, value: { source, path, prompt } };
  }
  if (source === "plain") return { ok: true, value: { source } };
  return { ok: false, error: "Choose a background: a pattern, a photo, AI art or a plain colour." };
}

/** A flyer design from the client or the database, checked; every error is a plain sentence for the organizer. */
export function parseFlyerDesign(raw: unknown): { ok: true; design: FlyerDesign } | { ok: false; error: string } {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return { ok: false, error: "The flyer design is missing. Reload the page and try again." };
  const o = raw as Record<string, unknown>;
  if (o.v !== undefined && o.v !== 1) return { ok: false, error: "This flyer design was saved by a newer version of the flyer maker. Reload the page." };
  const template = o.template;
  if (typeof template !== "string" || !(FLYER_TEMPLATES as readonly string[]).includes(template)) {
    return { ok: false, error: "Choose a template: Poster, Classic, Festival, Minimal or Photo." };
  }
  const size = o.size;
  if (typeof size !== "string" || !(FLYER_SIZE_KEYS as readonly string[]).includes(size)) {
    return { ok: false, error: "Choose a size: Post, Tall, Story or Print." };
  }
  const text = {
    headline: cleanLine(o.headline),
    tagline: cleanLine(o.tagline),
    date_line: cleanLine(o.date_line),
    venue_line: cleanLine(o.venue_line),
  };
  if (!text.headline) return { ok: false, error: "The headline is required." };
  for (const key of Object.keys(FLYER_LIMITS) as (keyof typeof FLYER_LIMITS)[]) {
    if (flyerTextLength(text[key]) > FLYER_LIMITS[key]) {
      const label = FIELD_LABEL[key];
      return { ok: false, error: `The ${label} is longer than ${FLYER_LIMITS[key]} characters.` };
    }
  }
  const bg = parseBackground(o.background);
  if (!bg.ok) return bg;
  if (template === "photo" && bg.value.source !== "photo" && bg.value.source !== "ai") {
    return { ok: false, error: "The Photo template needs a photo or AI art background." };
  }
  // The poster's content is checked strictly when the Poster is the template; otherwise it is only kept when it is valid.
  let poster: PosterContent | undefined;
  if (template === "poster" || o.poster !== undefined) {
    const p = parsePosterContent(o.poster);
    if (p.ok) poster = p.poster;
    else if (template === "poster") return p;
  }
  return {
    ok: true,
    design: {
      v: 1,
      template: template as FlyerTemplate,
      size: size as FlyerSize,
      ...text,
      show_qr: o.show_qr === true,
      background: bg.value,
      ...(poster ? { poster } : {}),
    },
  };
}

// ── Defaults ─────────────────────────────────────────────────────────────────

/** The description's first sentence (cut at the first . ! or ? followed by a space), or a word-boundary cut with "…". */
export function firstSentence(desc: string | null | undefined, max = 160): string {
  const text = (desc ?? "").replace(/\s+/g, " ").trim();
  if (!text) return "";
  const m = /[.!?](?=\s)/.exec(text);
  if (m && m.index + 1 <= max) return text.slice(0, m.index + 1);
  if (flyerTextLength(text) <= max) return text;
  const chars = Array.from(text).slice(0, Math.max(1, max - 1)).join("");
  const space = chars.lastIndexOf(" ");
  const cut = (space > max * 0.4 ? chars.slice(0, space) : chars).replace(/[\s,;:–—-]+$/, "");
  return `${cut}…`;
}

/** "Sat, Nov 8 · 6:00 PM–9:00 PM" in the community's time zone; "" without a start. */
export function flyerDateLine(startsAt: string | null | undefined, endsAt: string | null | undefined, tz: string, now: Date = new Date()): string {
  if (!startsAt || Number.isNaN(Date.parse(startsAt))) return "";
  const range = formatEventRange(startsAt, endsAt, tz, now);
  const end = endsAt && !Number.isNaN(Date.parse(endsAt)) ? formatTime(endsAt, tz) : null;
  return `${range} · ${formatTime(startsAt, tz)}${end ? `–${end}` : ""}`;
}

/** The pattern that suits an event, from its name. */
export function artMotifFor(name: string): FlyerPattern {
  const n = name.toLowerCase();
  if (/\bdiwali\b/.test(n)) return "diya";
  if (/\b(?:paryushan|samvatsari)/.test(n)) return "lotus";
  if (/\bnavratri\b/.test(n)) return "rangoli";
  return "mandala";
}

function cut(s: string, max: number): string {
  const chars = Array.from(s.replace(/\s+/g, " ").trim());
  return chars.length <= max ? chars.join("") : chars.slice(0, max).join("").trim();
}

/** "5:00 PM" and "9:00 PM" of one day → "5:00–9:00 PM" (AM or PM written once when both are in the same half of the day). */
function timeRange(start: string, end: string): string {
  const a = /^(.*)\s([AP]M)$/i.exec(start);
  const b = /^(.*)\s([AP]M)$/i.exec(end);
  return a && b && a[2].toUpperCase() === b[2].toUpperCase() ? `${a[1]}–${b[1]} ${b[2]}` : `${start}–${end}`;
}

/** An event that ends after midnight but within this many hours of its start is one evening (a Garba night), not two days. */
const ONE_EVENING_HOURS = 14;

/**
 * The ribbon's two lines in the community's time zone, from the event's start and end:
 *   no end (or an end that is not after the start)   "Saturday, October 3, 2026" / "5:00 PM onwards"
 *   one day                                         "Saturday, October 3, 2026" / "5:00–8:30 PM"
 *   one evening that runs past midnight             "Friday, October 16, 2026" / "7:00 PM–12:30 AM"
 *   several days                                    "September 10–16, 2026" / "6:00 PM onwards"
 * For several days the event records only the first day's start and the last day's end, so the time line gives
 * the start and nothing it cannot know (no "each day" and no end time). Empty without a start.
 */
export function posterWhen(startsAt: string | null | undefined, endsAt: string | null | undefined, tz: string): { date: string; time: string } {
  if (!startsAt || Number.isNaN(Date.parse(startsAt))) return { date: "", time: "" };
  const startMs = Date.parse(startsAt);
  const endMs = endsAt && !Number.isNaN(Date.parse(endsAt)) && Date.parse(endsAt) > startMs ? Date.parse(endsAt) : null;
  const parts = (ms: number) =>
    Object.fromEntries(
      new Intl.DateTimeFormat("en-US", { timeZone: tz, weekday: "long", year: "numeric", month: "long", day: "numeric" })
        .formatToParts(new Date(ms))
        .map((p) => [p.type, p.value]),
    ) as Record<string, string>;
  const clock = (ms: number) => formatTime(new Date(ms).toISOString(), tz).replace(/[\u00A0\u202F]/g, " ");
  const s = parts(startMs);
  const startDate = `${s.weekday}, ${s.month} ${s.day}, ${s.year}`;
  const onwards = `${clock(startMs)} onwards`;
  if (endMs === null) return { date: startDate, time: onwards };
  const e = parts(endMs);
  if (s.year === e.year && s.month === e.month && s.day === e.day) return { date: startDate, time: timeRange(clock(startMs), clock(endMs)) };
  if (endMs - startMs <= ONE_EVENING_HOURS * 3_600_000) return { date: startDate, time: `${clock(startMs)}–${clock(endMs)}` };
  const date =
    s.year !== e.year
      ? `${s.month} ${s.day}, ${s.year} – ${e.month} ${e.day}, ${e.year}`
      : s.month === e.month
        ? `${s.month} ${s.day}–${e.day}, ${s.year}`
        : `${s.month} ${s.day} – ${e.month} ${e.day}, ${s.year}`;
  return { date, time: onwards };
}

/** The description, cut at a sentence end (or a word) to fit `max` characters. */
function paragraphFrom(desc: string | null | undefined, max: number): string {
  const text = (desc ?? "").replace(/\s+/g, " ").trim();
  if (flyerTextLength(text) <= max) return text;
  const chars = Array.from(text).slice(0, max).join("");
  const end = Math.max(chars.lastIndexOf(". "), chars.lastIndexOf("! "), chars.lastIndexOf("? "));
  if (end > max * 0.5) return chars.slice(0, end + 1);
  return firstSentence(text, max);
}

/** A new poster for an event: its own words and date, the pack that suits its name, every optional section ready to fill. */
export function defaultPoster(e: { name: string; description: string | null; startsAt: string | null; endsAt: string | null; tz: string }): PosterContent {
  const when = posterWhen(e.startsAt, e.endsAt, e.tz);
  return {
    occasion: occasionFor(e.name, e.description),
    frame: { source: "code" },
    scene: { source: "code" },
    logo: true,
    partner: { on: false, label: "", sub: "", logo_path: null },
    subhead: "",
    slogan: "",
    stat: { on: false, icon: "people", label: "", value: "", caption: "" },
    ribbon: { on: true, date: cut(when.date, POSTER_LIMITS.ribbon_date), time: cut(when.time, POSTER_LIMITS.ribbon_time) },
    agenda: [],
    paragraph: cut(paragraphFrom(e.description, POSTER_LIMITS.paragraph), POSTER_LIMITS.paragraph),
    footer: "",
  };
}

export function defaultFlyerDesign(e: {
  name: string;
  description: string | null;
  venue: string | null;
  startsAt: string | null;
  endsAt: string | null;
  tz: string;
  qrAvailable: boolean;
  now?: Date;
}): FlyerDesign {
  return {
    v: 1,
    // Flyers v2: a new flyer starts as a Poster at the poster's own 2:3 size (the owner's reference); every template stays a click away.
    template: "poster",
    size: "tall",
    headline: cut(e.name, FLYER_LIMITS.headline) || "Upcoming event",
    tagline: cut(firstSentence(e.description), FLYER_LIMITS.tagline),
    date_line: cut(flyerDateLine(e.startsAt, e.endsAt, e.tz, e.now), FLYER_LIMITS.date_line),
    venue_line: cut(e.venue ?? "", FLYER_LIMITS.venue_line),
    show_qr: e.qrAvailable,
    background: { source: "pattern", pattern: artMotifFor(e.name) },
    poster: defaultPoster(e),
  };
}

// ── What the saved flyer was made for ────────────────────────────────────────
// The date and venue lines on a saved flyer are frozen text. When the flyer is
// saved, the portal also stores the event's own start, end and venue beside
// the design (events.flyer_design.made_for), so a later change to the event
// can be flagged: the flyer maker and the event's Details tab then say the
// flyer still shows the old date or venue.

export type FlyerMadeFor = { starts_at: string | null; ends_at: string | null; venue: string };

type EventWhenWhere = { starts_at: string | null; ends_at: string | null; venue: string | null };

/** The event's start, end and venue as they are now (what a flyer saved now is made for). */
export function flyerMadeFor(e: EventWhenWhere): FlyerMadeFor {
  const ts = (v: string | null) => (v && !Number.isNaN(Date.parse(v)) ? v : null);
  return { starts_at: ts(e.starts_at), ends_at: ts(e.ends_at), venue: (e.venue ?? "").replace(/\s+/g, " ").trim() };
}

/** flyer_design.made_for, read defensively; null when the design has none. */
export function readFlyerMadeFor(rawDesign: unknown): FlyerMadeFor | null {
  const o = rawDesign && typeof rawDesign === "object" && !Array.isArray(rawDesign) ? (rawDesign as Record<string, unknown>).made_for : null;
  if (!o || typeof o !== "object" || Array.isArray(o)) return null;
  const m = o as Record<string, unknown>;
  const str = (v: unknown) => (typeof v === "string" ? v : null);
  return flyerMadeFor({ starts_at: str(m.starts_at), ends_at: str(m.ends_at), venue: str(m.venue) });
}

/** Which of the event's date and venue changed after its designed flyer was saved (both false when there is no record). */
export function flyerOutOfDate(rawDesign: unknown, e: EventWhenWhere): { date: boolean; venue: boolean } {
  const made = readFlyerMadeFor(rawDesign);
  if (!made) return { date: false, venue: false };
  const now = flyerMadeFor(e);
  const same = (a: string | null, b: string | null) => (a === null || b === null ? a === b : Date.parse(a) === Date.parse(b));
  return { date: !same(made.starts_at, now.starts_at) || !same(made.ends_at, now.ends_at), venue: made.venue !== now.venue };
}

/** "date", "venue" or "date and venue" — what changed, for a sentence. */
export function outOfDateWhat(o: { date: boolean; venue: boolean }): string | null {
  return o.date && o.venue ? "date and venue" : o.date ? "date" : o.venue ? "venue" : null;
}

// ── AI background art ────────────────────────────────────────────────────────
// ── Identical copy of worker/src/flyer-guard.ts (kept equal by a test) ──────

/** Whole words, matched case-insensitively, each also with a plural ending (-s or -es). */
export const FLYER_ART_BLOCKED_TERMS: readonly string[] = [
  // People
  "people", "person", "persons", "man", "men", "woman", "women", "child", "children", "kid", "kids",
  "boy", "boys", "girl", "girls", "baby", "babies", "family", "families", "face", "faces", "portrait", "crowd",
  "human", "humans", "monk", "monks", "nun", "sadhu", "sadhvi", "maharaj", "maharajsaheb", "muni", "acharya",
  "guru", "saint", "devotee", "dancer", "lady", "ladies", "figurine",
  // Deities and idols
  "god", "gods", "goddess", "deity", "deities", "idol", "idols", "murti", "murtis", "statue", "statues",
  "bhagwan", "bhagavan", "prabhu", "tirthankar", "tirthankara", "jina", "mahavir", "mahavira",
  "parshvanath", "parasnath", "adinath", "rishabhdev", "neminath", "shantinath", "padmavati", "buddha", "krishna",
  "shiva", "ganesh", "ganesha", "lakshmi", "saraswati", "durga", "amba", "ambe", "ambaji", "mataji", "devi",
  "hanuman", "vishnu", "jesus",
  // Lettering
  "text", "letter", "letters", "lettering", "word", "words", "typography", "caption", "logo", "writing",
  "calligraphy", "font", "quote",
];

/** Always appended to the prompt, exactly once. */
export const FLYER_ART_GUARDRAIL =
  "Abstract decorative background art only. No text, no letters, no numbers, no words, no writing, no logos, no watermarks. " +
  "No people, no human figures, no faces, no hands. No deities, no gods, no idols, no murtis, no religious figures or statues. " +
  "Soft, elegant, festive ornamental patterns and light, with calm open space for text to be added later.";

const BLOCKED = new RegExp(`\\b(?:${FLYER_ART_BLOCKED_TERMS.join("|")})(?:e?s)?\\b`, "i");

/** Always the LAST sentence of a Poster art layer's prompt, exactly once. */
export const FLYER_LAYER_GUARDRAIL =
  "No text of any kind: no letters, no numbers, no words, no writing, no signs, no labels, no logos, no watermarks. " +
  "No deities, no gods, no idols, no murtis, no religious figures or statues. " +
  "No close-up faces, no portraits, no hands, and no people in the foreground.";

/** The prompt without any copy of either guardrail (the guardrails themselves name the blocked words). */
export function stripArtGuardrail(text: string): string {
  return text.split(FLYER_ART_GUARDRAIL).join(" ").split(FLYER_LAYER_GUARDRAIL).join(" ").replace(/\s{2,}/g, " ").trim();
}

/** The first blocked word in the organizer's own text (as they typed it), or null. */
export function findBlockedArtTerm(text: string): string | null {
  const m = BLOCKED.exec(stripArtGuardrail(text));
  return m ? m[0] : null;
}

/** The organizer's text with the guardrail appended once; idempotent. Never longer than `max`: the guardrail is never cut. */
export function withArtGuardrail(text: string, max = 2000): string {
  const room = Math.max(0, max - FLYER_ART_GUARDRAIL.length - 1);
  const base = stripArtGuardrail(text).slice(0, room).trim();
  return base ? `${base} ${FLYER_ART_GUARDRAIL}` : FLYER_ART_GUARDRAIL;
}

/** A Poster layer's prompt ending with FLYER_LAYER_GUARDRAIL exactly once; idempotent. Never longer than `max`: the guardrail is never cut. */
export function withLayerGuardrail(text: string, max = 2000): string {
  const room = Math.max(0, max - FLYER_LAYER_GUARDRAIL.length - 1);
  const base = stripArtGuardrail(text).slice(0, room).trim();
  return base ? `${base} ${FLYER_LAYER_GUARDRAIL}` : FLYER_LAYER_GUARDRAIL;
}

// ── End of the copy ──────────────────────────────────────────────────────────

/** The longest art description an organizer may type (the guardrail is added after it, within the 2,000-character job limit). */
export const FLYER_ART_PROMPT_MAX = 1200;

const NAMED_COLORS: readonly { name: string; rgb: [number, number, number] }[] = [
  { name: "deep navy", rgb: [0x1b, 0x2c, 0x5c] },
  { name: "royal blue", rgb: [0x2f, 0x5b, 0xd3] },
  { name: "sky blue", rgb: [0x7f, 0xb8, 0xe6] },
  { name: "teal", rgb: [0x1f, 0x7a, 0x7a] },
  { name: "emerald green", rgb: [0x1f, 0x7a, 0x4d] },
  { name: "sage green", rgb: [0x9c, 0xb8, 0x9a] },
  { name: "saffron", rgb: [0xe0, 0x82, 0x1c] },
  { name: "marigold gold", rgb: [0xe6, 0xb4, 0x2c] },
  { name: "maroon", rgb: [0x7a, 0x2e, 0x1f] },
  { name: "crimson red", rgb: [0xc0, 0x26, 0x2d] },
  { name: "rose pink", rgb: [0xe5, 0x8f, 0xa8] },
  { name: "plum purple", rgb: [0x5b, 0x4b, 0x8a] },
  { name: "ivory cream", rgb: [0xfb, 0xf7, 0xf0] },
  { name: "charcoal grey", rgb: [0x3a, 0x3a, 0x3a] },
];

/** The nearest of a dozen named colours, for a prompt ("saffron", "deep navy"); "warm" when the value is not a hex colour. */
export function colorWord(hex: string): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return "warm";
  const n = parseInt(m[1], 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  let best = NAMED_COLORS[0];
  let bestD = Infinity;
  for (const c of NAMED_COLORS) {
    // Weighted RGB distance ("redmean"), close enough to how people see colour for naming.
    const rm = (r + c.rgb[0]) / 2;
    const dr = r - c.rgb[0];
    const dg = g - c.rgb[1];
    const db = b - c.rgb[2];
    const d = (2 + rm / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rm) / 256) * db * db;
    if (d < bestD) {
      bestD = d;
      best = c;
    }
  }
  return best.name;
}

const MOTIF_ART: Record<FlyerPattern, string> = {
  diya: "rows of small glowing oil lamps as soft points of golden light over a gentle dotted pattern",
  lotus: "stylised lotus petals and soft concentric water ripples",
  rangoli: "a symmetrical rangoli rosette of petals, dots and fine curved lines",
  mandala: "concentric mandala rings of petals and fine geometric lines",
};

/**
 * The starting description for AI background art: the event's motif in the
 * brand's named colours. Abstract and decorative only, and it never includes
 * the event's name (names such as "Mahavir Jayanti" would invite a figure).
 * The guardrail is added when the art is requested (withArtGuardrail).
 */
export function buildFlyerArtPrompt(e: { eventName: string; primary: string; accent: string }): string {
  const motif = artMotifFor(e.eventName);
  const primary = colorWord(e.primary);
  const accent = colorWord(e.accent);
  const colours = primary === accent ? `${primary} tones` : `${primary} and ${accent} tones`;
  return `An elegant, festive background of ${MOTIF_ART[motif]}, in ${colours}, softly lit, with a smooth gradient and generous calm space in the middle.`;
}

/** A Poster layer job's own key parts (null: a background request). */
export type ArtJobLayer = { layer: FlyerLayerKind; occasion: FlyerOccasion; seed: number } | null;

/** What the background service's job says (app.events_request_flyer(_art) / app.events_flyer_result), read on the server. */
export type ArtJob =
  | { status: "queued" | "running" }
  | { status: "image"; imageB64: string; contentType: string; prompt: string; layer: ArtJobLayer }
  | { status: "stored"; storedPath: string; prompt: string; layer: ArtJobLayer }
  | { status: "failed" | "unavailable"; reason: string }
  | { status: "none" };

function readJobLayer(r: Record<string, unknown>): ArtJobLayer {
  const seed = Number(r.seed);
  if ((r.layer === "frame" || r.layer === "scene") && isFlyerOccasion(r.occasion) && Number.isInteger(seed) && seed >= 1 && seed <= FLYER_ART_SEED_MAX) {
    return { layer: r.layer, occasion: r.occasion, seed };
  }
  return null;
}

export function readArtJob(d: unknown): ArtJob {
  const o = (d ?? {}) as Record<string, unknown>;
  const status = typeof o.status === "string" ? o.status : "";
  if (status === "queued" || status === "running") return { status };
  if (status === "unavailable") return { status, reason: typeof o.reason === "string" && o.reason ? o.reason : "The background service is not available." };
  if (status === "failed" || status === "cancelled") {
    return { status: "failed", reason: typeof o.error === "string" && o.error ? o.error : "The background service could not make the art." };
  }
  if (status === "missing") return { status: "failed", reason: "The background service no longer has this request. Generate the art again." };
  if (status === "done") {
    const r = (o.result ?? {}) as Record<string, unknown>;
    const prompt = typeof r.prompt === "string" ? r.prompt : "";
    const layer = readJobLayer(r);
    if (typeof r.stored_path === "string" && r.stored_path) return { status: "stored", storedPath: r.stored_path, prompt, layer };
    if (typeof r.image_b64 === "string" && r.image_b64) {
      return { status: "image", imageB64: r.image_b64, contentType: typeof r.content_type === "string" ? r.content_type : "", prompt, layer };
    }
    return { status: "failed", reason: "The background service finished but did not return any art." };
  }
  return { status: "none" };
}

/** The AI art step as the flyer panel sees it — never the image bytes, only a stored file and a short-lived URL. */
export type FlyerArtState =
  | { status: "queued" | "running" }
  | { status: "ready"; artPath: string; artUrl: string; layer?: FlyerLayerKind }
  | { status: "failed" | "unavailable"; reason: string }
  | { status: "none" };

// ── Small helpers ────────────────────────────────────────────────────────────

/** "diwali-mela-flyer-post.png" */
export function flyerFileName(eventName: string, size: FlyerSize, ext: "png" | "pdf"): string {
  const slug = eventName
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/-+$/g, "");
  return `${slug || "event"}-flyer-${size}.${ext}`;
}

/** The member app's link for an event (what the QR code opens), or null when the member web app's address is not an http(s) address. */
export function memberAppEventLink(base: string | null | undefined, eventId: string): string | null {
  const b = (base ?? "").trim().replace(/\/+$/, "");
  if (!/^https?:\/\/[^\s/?#]+(?:\/[^\s?#]*)?$/i.test(b)) return null;
  return `${b}/e/${eventId}`;
}

/** How many ordinary letters' room a text takes: a capital counts as 1.3 (an ALL-CAPS headline is about a third wider). */
export function flyerTextRoom(s: string): number {
  let room = 0;
  for (const ch of s) room += ch !== ch.toLowerCase() ? 1.3 : 1;
  return room;
}

/**
 * A font size (in the flyer's units) that keeps longer text inside its box:
 * `base` up to `comfortableChars` characters' room (flyerTextRoom), then
 * scaled down by the square root of the overflow (text wraps onto more lines,
 * so area is what grows), never below `floor` (55%) of `base`. A length
 * heuristic, not a measurement.
 */
export function fitFontSize(text: string, comfortableChars: number, base: number, floor = 0.55): number {
  const len = flyerTextRoom(text.trim());
  if (len <= comfortableChars || comfortableChars <= 0) return base;
  const size = base * Math.sqrt(comfortableChars / len);
  return Math.round(Math.max(base * floor, size) * 10) / 10;
}
