// Event flyers — the flyer maker's pure parts (no server imports: the flyer
// panel is a client component and imports this file).
//
// A flyer is DESIGNED from the brand kit (owner decisions 2026-10-01): a
// template, a size, the words (headline, tagline, date line, venue line), an
// RSVP QR code, and one background — a pattern drawn in code, a photo from the
// community's approved albums, free AI background art, or a plain colour. The
// design is stored on the event as events.flyer_design (v1, migration 0578)
// and rendered server-side to a PNG (src/lib/events/flyer-render.tsx).
//
// AI art is background art only: no text, letters, people, deities, idols or
// murtis. FLYER_ART_BLOCKED_TERMS and FLYER_ART_GUARDRAIL below are an exact
// copy of worker/src/flyer-guard.ts (tests/events-flyer.test.ts keeps them
// equal), so the portal refuses what the worker would refuse, before asking.

import { formatEventRange, formatTime } from "./format";

// ── Sources, templates, sizes, backgrounds ──────────────────────────────────

export type FlyerSource = "manual" | "ai" | "designed";

/** The events.flyer_source column, read defensively (it is a plain `text` column at the DB). */
export function readFlyerSource(v: string | null): FlyerSource | null {
  return v === "manual" || v === "ai" || v === "designed" ? v : null;
}

export const FLYER_SOURCE_LABEL: Record<FlyerSource, string> = {
  designed: "Made with the flyer maker",
  manual: "Uploaded",
  ai: "Generated by AI (earlier flyer)",
};

export type FlyerTemplate = "classic" | "festival" | "minimal" | "photo";
export const FLYER_TEMPLATES: readonly FlyerTemplate[] = ["classic", "festival", "minimal", "photo"];
export const FLYER_TEMPLATE_LABEL: Record<FlyerTemplate, string> = {
  classic: "Classic",
  festival: "Festival",
  minimal: "Minimal",
  photo: "Photo",
};

export type FlyerSize = "post" | "story" | "print";
export const FLYER_SIZES = {
  post: { w: 1080, h: 1350, label: "Post 1080×1350" },
  story: { w: 1080, h: 1920, label: "Story 1080×1920" },
  print: { w: 2550, h: 3300, label: "Print — US Letter (PDF)" },
} as const satisfies Record<FlyerSize, { w: number; h: number; label: string }>;
export const FLYER_SIZE_KEYS: readonly FlyerSize[] = ["post", "story", "print"];

export type FlyerPattern = "lotus" | "rangoli" | "diya" | "mandala";
export const FLYER_PATTERNS: readonly FlyerPattern[] = ["lotus", "rangoli", "diya", "mandala"];
export const FLYER_PATTERN_LABEL: Record<FlyerPattern, string> = { lotus: "Lotus", rangoli: "Rangoli", diya: "Diya", mandala: "Mandala" };

export type FlyerBackground =
  | { source: "pattern"; pattern: FlyerPattern }
  | { source: "photo"; photo_id: string }
  | { source: "ai"; path: string; prompt: string }
  | { source: "plain" };

/** events.flyer_design, v1 (contract C2, migration 0578). */
export type FlyerDesign = {
  v: 1;
  template: FlyerTemplate;
  size: FlyerSize;
  headline: string;
  tagline: string;
  date_line: string;
  venue_line: string;
  show_qr: boolean;
  background: FlyerBackground;
};

export const FLYER_LIMITS = { headline: 90, tagline: 180, date_line: 90, venue_line: 120 } as const;
const FIELD_LABEL: Record<keyof typeof FLYER_LIMITS, string> = {
  headline: "headline",
  tagline: "tagline",
  date_line: "date line",
  venue_line: "venue line",
};

/** Characters as a person counts them (code points, so a Gujarati letter with its sign counts per symbol, not per UTF-16 unit). */
export function flyerTextLength(s: string): number {
  return Array.from(s).length;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ART_PATH = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/events\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\/art-\d{1,16}\.(?:jpg|png)$/i;

/** Is this the storage key of THIS event's AI background art (content/<center>/events/<event>/art-<ms>.<jpg|png>)? */
export function isFlyerArtPath(path: string, centerId: string, eventId: string): boolean {
  return ART_PATH.test(path) && path.toLowerCase().startsWith(`${centerId}/events/${eventId}/art-`.toLowerCase());
}

function cleanLine(v: unknown): string {
  // Control characters (tabs, line breaks) become spaces: the flyer lays out its own lines.
  return typeof v === "string" ? v.replace(/[\u0000-\u001F\u007F]+/g, " ").replace(/ {2,}/g, " ").trim() : "";
}

function parseBackground(raw: unknown): { ok: true; value: FlyerBackground } | { ok: false; error: string } {
  const o = raw && typeof raw === "object" && !Array.isArray(raw) ? (raw as Record<string, unknown>) : null;
  const source = o?.source;
  if (source === "pattern") {
    const p = o?.pattern;
    if (typeof p === "string" && (FLYER_PATTERNS as readonly string[]).includes(p)) return { ok: true, value: { source, pattern: p as FlyerPattern } };
    return { ok: false, error: "Choose one of the patterns: lotus, rangoli, diya or mandala." };
  }
  if (source === "photo") {
    const id = o?.photo_id;
    if (typeof id === "string" && UUID.test(id)) return { ok: true, value: { source, photo_id: id.toLowerCase() } };
    return { ok: false, error: "Choose a photo from one of the albums." };
  }
  if (source === "ai") {
    const path = typeof o?.path === "string" ? o.path.trim() : "";
    if (!ART_PATH.test(path)) return { ok: false, error: "Generate the AI art first, or choose another background." };
    const prompt = typeof o?.prompt === "string" ? o.prompt.trim().slice(0, 2000) : "";
    return { ok: true, value: { source, path, prompt } };
  }
  if (source === "plain") return { ok: true, value: { source } };
  return { ok: false, error: "Choose a background: a pattern, a photo, AI art or a plain colour." };
}

/** A flyer design from the client or the database, checked; every error is a plain sentence for the organizer. */
export function parseFlyerDesign(raw: unknown): { ok: true; design: FlyerDesign } | { ok: false; error: string } {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return { ok: false, error: "The flyer design is missing. Reload the page and try again." };
  const o = raw as Record<string, unknown>;
  if (o.v !== undefined && o.v !== 1) return { ok: false, error: "This flyer design was saved by a newer version of the flyer maker. Reload the page." };
  const template = o.template;
  if (typeof template !== "string" || !(FLYER_TEMPLATES as readonly string[]).includes(template)) {
    return { ok: false, error: "Choose a template: Classic, Festival, Minimal or Photo." };
  }
  const size = o.size;
  if (typeof size !== "string" || !(FLYER_SIZE_KEYS as readonly string[]).includes(size)) {
    return { ok: false, error: "Choose a size: Post, Story or Print." };
  }
  const text = {
    headline: cleanLine(o.headline),
    tagline: cleanLine(o.tagline),
    date_line: cleanLine(o.date_line),
    venue_line: cleanLine(o.venue_line),
  };
  if (!text.headline) return { ok: false, error: "The headline is required." };
  for (const key of Object.keys(FLYER_LIMITS) as (keyof typeof FLYER_LIMITS)[]) {
    if (flyerTextLength(text[key]) > FLYER_LIMITS[key]) {
      const label = FIELD_LABEL[key];
      return { ok: false, error: `The ${label} is longer than ${FLYER_LIMITS[key]} characters.` };
    }
  }
  const bg = parseBackground(o.background);
  if (!bg.ok) return bg;
  if (template === "photo" && bg.value.source !== "photo" && bg.value.source !== "ai") {
    return { ok: false, error: "The Photo template needs a photo or AI art background." };
  }
  return {
    ok: true,
    design: {
      v: 1,
      template: template as FlyerTemplate,
      size: size as FlyerSize,
      ...text,
      show_qr: o.show_qr === true,
      background: bg.value,
    },
  };
}

// ── Defaults ─────────────────────────────────────────────────────────────────

/** The description's first sentence (cut at the first . ! or ? followed by a space), or a word-boundary cut with "…". */
export function firstSentence(desc: string | null | undefined, max = 160): string {
  const text = (desc ?? "").replace(/\s+/g, " ").trim();
  if (!text) return "";
  const m = /[.!?](?=\s)/.exec(text);
  if (m && m.index + 1 <= max) return text.slice(0, m.index + 1);
  if (flyerTextLength(text) <= max) return text;
  const chars = Array.from(text).slice(0, Math.max(1, max - 1)).join("");
  const space = chars.lastIndexOf(" ");
  const cut = (space > max * 0.4 ? chars.slice(0, space) : chars).replace(/[\s,;:–—-]+$/, "");
  return `${cut}…`;
}

/** "Sat, Nov 8 · 6:00 PM–9:00 PM" in the community's time zone; "" without a start. */
export function flyerDateLine(startsAt: string | null | undefined, endsAt: string | null | undefined, tz: string, now: Date = new Date()): string {
  if (!startsAt || Number.isNaN(Date.parse(startsAt))) return "";
  const range = formatEventRange(startsAt, endsAt, tz, now);
  const end = endsAt && !Number.isNaN(Date.parse(endsAt)) ? formatTime(endsAt, tz) : null;
  return `${range} · ${formatTime(startsAt, tz)}${end ? `–${end}` : ""}`;
}

/** The pattern that suits an event, from its name. */
export function artMotifFor(name: string): FlyerPattern {
  const n = name.toLowerCase();
  if (/\bdiwali\b/.test(n)) return "diya";
  if (/\b(?:paryushan|samvatsari)/.test(n)) return "lotus";
  if (/\bnavratri\b/.test(n)) return "rangoli";
  return "mandala";
}

function cut(s: string, max: number): string {
  const chars = Array.from(s.replace(/\s+/g, " ").trim());
  return chars.length <= max ? chars.join("") : chars.slice(0, max).join("").trim();
}

export function defaultFlyerDesign(e: {
  name: string;
  description: string | null;
  venue: string | null;
  startsAt: string | null;
  endsAt: string | null;
  tz: string;
  qrAvailable: boolean;
  now?: Date;
}): FlyerDesign {
  return {
    v: 1,
    template: "classic",
    size: "post",
    headline: cut(e.name, FLYER_LIMITS.headline) || "Upcoming event",
    tagline: cut(firstSentence(e.description), FLYER_LIMITS.tagline),
    date_line: cut(flyerDateLine(e.startsAt, e.endsAt, e.tz, e.now), FLYER_LIMITS.date_line),
    venue_line: cut(e.venue ?? "", FLYER_LIMITS.venue_line),
    show_qr: e.qrAvailable,
    background: { source: "pattern", pattern: artMotifFor(e.name) },
  };
}

// ── AI background art ────────────────────────────────────────────────────────
// ── Identical copy of worker/src/flyer-guard.ts (kept equal by a test) ──────

/** Whole words, matched case-insensitively. */
export const FLYER_ART_BLOCKED_TERMS: readonly string[] = [
  // People
  "people", "person", "persons", "man", "men", "woman", "women", "child", "children", "kid", "kids",
  "boy", "boys", "girl", "girls", "baby", "family", "families", "face", "faces", "portrait", "crowd",
  "human", "humans", "monk", "monks", "nun", "sadhu", "sadhvi", "maharaj", "maharajsaheb",
  // Deities and idols
  "god", "gods", "goddess", "deity", "deities", "idol", "idols", "murti", "murtis", "statue", "statues",
  "bhagwan", "bhagavan", "prabhu", "tirthankar", "tirthankara", "jina", "mahavir", "mahavira",
  "parshvanath", "parasnath", "adinath", "rishabhdev", "neminath", "shantinath", "buddha", "krishna",
  "shiva", "ganesh", "ganesha", "lakshmi", "saraswati", "jesus",
  // Lettering
  "text", "letter", "letters", "lettering", "word", "words", "typography", "caption", "logo", "writing",
  "calligraphy", "font", "quote",
];

/** Always appended to the prompt, exactly once. */
export const FLYER_ART_GUARDRAIL =
  "Abstract decorative background art only. No text, no letters, no numbers, no words, no writing, no logos, no watermarks. " +
  "No people, no human figures, no faces, no hands. No deities, no gods, no idols, no murtis, no religious figures or statues. " +
  "Soft, elegant, festive ornamental patterns and light, with calm open space for text to be added later.";

const BLOCKED = new RegExp(`\\b(?:${FLYER_ART_BLOCKED_TERMS.join("|")})\\b`, "i");

/** The prompt without any copy of the guardrail (the guardrail itself names the blocked words). */
export function stripArtGuardrail(text: string): string {
  return text.split(FLYER_ART_GUARDRAIL).join(" ").replace(/\s{2,}/g, " ").trim();
}

/** The first blocked word in the organizer's own text (as they typed it), or null. */
export function findBlockedArtTerm(text: string): string | null {
  const m = BLOCKED.exec(stripArtGuardrail(text));
  return m ? m[0] : null;
}

/** The organizer's text with the guardrail appended once; idempotent. Never longer than `max`: the guardrail is never cut. */
export function withArtGuardrail(text: string, max = 2000): string {
  const room = Math.max(0, max - FLYER_ART_GUARDRAIL.length - 1);
  const base = stripArtGuardrail(text).slice(0, room).trim();
  return base ? `${base} ${FLYER_ART_GUARDRAIL}` : FLYER_ART_GUARDRAIL;
}

// ── End of the copy ──────────────────────────────────────────────────────────

/** The longest art description an organizer may type (the guardrail is added after it, within the 2,000-character job limit). */
export const FLYER_ART_PROMPT_MAX = 1200;

const NAMED_COLORS: readonly { name: string; rgb: [number, number, number] }[] = [
  { name: "deep navy", rgb: [0x1b, 0x2c, 0x5c] },
  { name: "royal blue", rgb: [0x2f, 0x5b, 0xd3] },
  { name: "sky blue", rgb: [0x7f, 0xb8, 0xe6] },
  { name: "teal", rgb: [0x1f, 0x7a, 0x7a] },
  { name: "emerald green", rgb: [0x1f, 0x7a, 0x4d] },
  { name: "sage green", rgb: [0x9c, 0xb8, 0x9a] },
  { name: "saffron", rgb: [0xe0, 0x82, 0x1c] },
  { name: "marigold gold", rgb: [0xe6, 0xb4, 0x2c] },
  { name: "maroon", rgb: [0x7a, 0x2e, 0x1f] },
  { name: "crimson red", rgb: [0xc0, 0x26, 0x2d] },
  { name: "rose pink", rgb: [0xe5, 0x8f, 0xa8] },
  { name: "plum purple", rgb: [0x5b, 0x4b, 0x8a] },
  { name: "ivory cream", rgb: [0xfb, 0xf7, 0xf0] },
  { name: "charcoal grey", rgb: [0x3a, 0x3a, 0x3a] },
];

/** The nearest of a dozen named colours, for a prompt ("saffron", "deep navy"); "warm" when the value is not a hex colour. */
export function colorWord(hex: string): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return "warm";
  const n = parseInt(m[1], 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  let best = NAMED_COLORS[0];
  let bestD = Infinity;
  for (const c of NAMED_COLORS) {
    // Weighted RGB distance ("redmean"), close enough to how people see colour for naming.
    const rm = (r + c.rgb[0]) / 2;
    const dr = r - c.rgb[0];
    const dg = g - c.rgb[1];
    const db = b - c.rgb[2];
    const d = (2 + rm / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rm) / 256) * db * db;
    if (d < bestD) {
      bestD = d;
      best = c;
    }
  }
  return best.name;
}

const MOTIF_ART: Record<FlyerPattern, string> = {
  diya: "rows of small glowing oil lamps as soft points of golden light over a gentle dotted pattern",
  lotus: "stylised lotus petals and soft concentric water ripples",
  rangoli: "a symmetrical rangoli rosette of petals, dots and fine curved lines",
  mandala: "concentric mandala rings of petals and fine geometric lines",
};

/**
 * The starting description for AI background art: the event's motif in the
 * brand's named colours. Abstract and decorative only, and it never includes
 * the event's name (names such as "Mahavir Jayanti" would invite a figure).
 * The guardrail is added when the art is requested (withArtGuardrail).
 */
export function buildFlyerArtPrompt(e: { eventName: string; primary: string; accent: string }): string {
  const motif = artMotifFor(e.eventName);
  const primary = colorWord(e.primary);
  const accent = colorWord(e.accent);
  const colours = primary === accent ? `${primary} tones` : `${primary} and ${accent} tones`;
  return `An elegant, festive background of ${MOTIF_ART[motif]}, in ${colours}, softly lit, with a smooth gradient and generous calm space in the middle.`;
}

/** What the background service's job says (app.events_request_flyer / app.events_flyer_result), read on the server. */
export type ArtJob =
  | { status: "queued" | "running" }
  | { status: "image"; imageB64: string; contentType: string; prompt: string }
  | { status: "stored"; storedPath: string; prompt: string }
  | { status: "failed" | "unavailable"; reason: string }
  | { status: "none" };

export function readArtJob(d: unknown): ArtJob {
  const o = (d ?? {}) as Record<string, unknown>;
  const status = typeof o.status === "string" ? o.status : "";
  if (status === "queued" || status === "running") return { status };
  if (status === "unavailable") return { status, reason: typeof o.reason === "string" && o.reason ? o.reason : "The background service is not available." };
  if (status === "failed" || status === "cancelled") {
    return { status: "failed", reason: typeof o.error === "string" && o.error ? o.error : "The background service could not make the art." };
  }
  if (status === "missing") return { status: "failed", reason: "The background service no longer has this request. Generate the art again." };
  if (status === "done") {
    const r = (o.result ?? {}) as Record<string, unknown>;
    const prompt = typeof r.prompt === "string" ? r.prompt : "";
    if (typeof r.stored_path === "string" && r.stored_path) return { status: "stored", storedPath: r.stored_path, prompt };
    if (typeof r.image_b64 === "string" && r.image_b64) {
      return { status: "image", imageB64: r.image_b64, contentType: typeof r.content_type === "string" ? r.content_type : "", prompt };
    }
    return { status: "failed", reason: "The background service finished but did not return any art." };
  }
  return { status: "none" };
}

/** The AI art step as the flyer panel sees it — never the image bytes, only a stored file and a short-lived URL. */
export type FlyerArtState =
  | { status: "queued" | "running" }
  | { status: "ready"; artPath: string; artUrl: string }
  | { status: "failed" | "unavailable"; reason: string }
  | { status: "none" };

// ── Small helpers ────────────────────────────────────────────────────────────

/** "diwali-mela-flyer-post.png" */
export function flyerFileName(eventName: string, size: FlyerSize, ext: "png" | "pdf"): string {
  const slug = eventName
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/-+$/g, "");
  return `${slug || "event"}-flyer-${size}.${ext}`;
}

/** The member app's link for an event (what the QR code opens), or null when the member web app's address is not an http(s) address. */
export function memberAppEventLink(base: string | null | undefined, eventId: string): string | null {
  const b = (base ?? "").trim().replace(/\/+$/, "");
  if (!/^https?:\/\/[^\s/?#]+(?:\/[^\s?#]*)?$/i.test(b)) return null;
  return `${b}/e/${eventId}`;
}

/**
 * A font size (in the flyer's units) that keeps longer text inside its box:
 * `base` up to `comfortableChars` characters, then scaled down by the square
 * root of the overflow (text wraps onto more lines, so area is what grows),
 * never below 55% of `base`. A length heuristic, not a measurement.
 */
export function fitFontSize(text: string, comfortableChars: number, base: number): number {
  const len = flyerTextLength(text.trim());
  if (len <= comfortableChars || comfortableChars <= 0) return base;
  const size = base * Math.sqrt(comfortableChars / len);
  return Math.round(Math.max(base * 0.55, size) * 10) / 10;
}
