"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";

import { ActionForm } from "@/components/action-form";
import { Modal } from "@/components/modal";
import { useToast } from "@/components/toast";
import { Alert, Card, buttonClass } from "@/components/ui";
import type { FlyerState } from "@/lib/events/flyer";

import { applyGeneratedFlyerAction, flyerGenerationResultAction, removeEventFlyerAction, requestEventFlyerAction, uploadEventFlyerAction } from "./flyer-actions";

type Pending = { imageB64: string; contentType: string; model: string; prompt: string };

/**
 * Event builder › Flyer: generate one with AI (editable prompt, preview,
 * regenerate) alongside a plain manual upload — mirrors the setup module's
 * brand-kit upload cards (setup/profile/page.tsx), plus the import module's
 * "ask the background service, poll, show the result" flow
 * (settings/import/new/wizard.tsx askAi()).
 */
export function FlyerPanel({
  eventId,
  flyerPath,
  flyerSource,
  flyerPrompt,
  promptSeed,
  previewUrl,
  previewError,
  editable,
}: {
  eventId: string;
  flyerPath: string;
  flyerSource: "manual" | "ai" | null;
  flyerPrompt: string | null;
  promptSeed: string;
  previewUrl: string | null;
  previewError: string | null;
  editable: boolean;
}) {
  const router = useRouter();
  const toast = useToast();
  const [prompt, setPrompt] = useState(flyerPrompt || promptSeed);
  const [gen, setGen] = useState<FlyerState | null>(null);
  const [pending, setPendingPreview] = useState<Pending | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [confirmApply, setConfirmApply] = useState<Pending | null>(null);
  const [busy, start] = useTransition();

  const hasFlyer = Boolean(flyerPath);
  const label = flyerSource === "ai" ? "Generated by AI" : flyerSource === "manual" ? "Uploaded manually" : null;
  const generateLabel = busy ? (gen?.status === "queued" || gen?.status === "running" ? "Generating…" : "Working…") : hasFlyer ? "Generate a new flyer" : "Generate flyer";

  function generate() {
    if (!prompt.trim()) {
      setError("Describe the flyer you want, in a sentence or two.");
      return;
    }
    setError(null);
    setPendingPreview(null);
    start(async () => {
      try {
        const res = await requestEventFlyerAction(eventId, prompt);
        if (!res.ok) {
          setError(res.error);
          setGen(null);
          return;
        }
        let state = res.data!;
        setGen(state);
        // Poll for up to two minutes: image generation is slower than the mapping-suggestion jobs.
        for (let i = 0; i < 60 && (state.status === "queued" || state.status === "running"); i++) {
          await new Promise((r) => setTimeout(r, 2000));
          const next = await flyerGenerationResultAction(eventId);
          if (!next.ok) {
            setError(next.error);
            setGen(null);
            return;
          }
          state = next.data!;
          setGen(state);
        }
        if (state.status === "queued" || state.status === "running") {
          setError("The background service has not answered within two minutes. Try again shortly, or upload a flyer instead.");
          return;
        }
        if (state.status === "unavailable" || state.status === "failed") {
          setError(state.reason);
          return;
        }
        if (state.status === "done") {
          setPendingPreview({ imageB64: state.imageB64, contentType: state.contentType, model: state.model, prompt: state.prompt });
        }
      } catch (err) {
        console.error("[events/flyer] generate failed:", err);
        setError("Could not generate the flyer — the server did not respond.");
      }
    });
  }

  function applyPending(p: Pending) {
    start(async () => {
      try {
        const res = await applyGeneratedFlyerAction(eventId, p.imageB64, p.contentType, p.model, p.prompt);
        if (!res.ok) {
          setError(res.error);
          toast?.show(res.error, "bad");
          return;
        }
        toast?.show(res.message ?? "Flyer saved.", "ok");
        setPendingPreview(null);
        setGen(null);
        router.refresh();
      } catch (err) {
        console.error("[events/flyer] apply failed:", err);
        setError("Could not save the generated flyer — the server did not respond.");
      }
    });
  }

  function acceptFlyer(p: Pending) {
    if (hasFlyer) {
      setConfirmApply(p);
      return;
    }
    applyPending(p);
  }

  if (!editable) return null;

  return (
    <Card span={4} title="Flyer" description="Generate one with AI, or upload your own">
      <div className="flex flex-col gap-3">
        {hasFlyer ? (
          <div>
            {previewUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={previewUrl} alt="Current event flyer" className="w-full rounded-[10px] border border-line" />
            ) : previewError ? (
              <Alert tone="danger">{previewError}</Alert>
            ) : (
              <p className="crm-hint">Loading the current flyer…</p>
            )}
            {label ? <p className="crm-hint mt-1">{label}</p> : null}
            <ActionForm
              action={removeEventFlyerAction.bind(null, eventId)}
              submitLabel="Remove flyer"
              variant="ghost"
              size="xs"
              buttonsClassName="mt-1"
              confirmMessage={"Remove this event's flyer?\nThe file stays in storage; the event just stops using it."}
            />
          </div>
        ) : (
          <p className="crm-hint">No flyer yet.</p>
        )}

        <div className="rounded-[10px] border border-line-soft bg-ground p-3">
          <p className="text-[13px] font-bold">Generate with AI</p>
          <label htmlFor="flyer-prompt" className="crm-label mt-1">
            Prompt
          </label>
          <textarea id="flyer-prompt" rows={4} value={prompt} onChange={(e) => setPrompt(e.target.value)} className="crm-input" disabled={busy} />
          <button type="button" className={buttonClass("primary", "sm")} onClick={generate} disabled={busy}>
            {generateLabel}
          </button>
          {error ? (
            <p role="alert" className="mt-2 rounded-[10px] border border-danger/30 bg-danger-50 px-3 py-2 text-[13px] text-danger">
              {error}
            </p>
          ) : null}
          {pending ? (
            <div className="mt-3">
              <p className="crm-hint mb-1">Preview — not saved yet</p>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={`data:${pending.contentType};base64,${pending.imageB64}`} alt="Generated flyer preview" className="w-full rounded-[10px] border border-line" />
              <div className="mt-2 flex flex-wrap gap-2">
                <button type="button" className={buttonClass("ok", "sm")} onClick={() => acceptFlyer(pending)} disabled={busy}>
                  Use this flyer
                </button>
                <button type="button" className={buttonClass("ghost", "sm")} onClick={generate} disabled={busy}>
                  Regenerate
                </button>
                <button type="button" className={buttonClass("ghost", "sm")} onClick={() => setPendingPreview(null)} disabled={busy}>
                  Discard
                </button>
              </div>
            </div>
          ) : null}
        </div>

        <div className="rounded-[10px] border border-line-soft bg-ground p-3">
          <p className="text-[13px] font-bold">Upload your own</p>
          <ActionForm
            action={uploadEventFlyerAction}
            submitLabel={hasFlyer ? "Replace" : "Upload"}
            pendingLabel="Uploading…"
            size="sm"
            resetOnSuccess
            buttonsClassName="mt-2"
            confirmMessage={hasFlyer ? "Replace the current flyer with this file?" : undefined}
          >
            <input type="hidden" name="event_id" value={eventId} />
            <input name="file" type="file" accept="image/png,image/jpeg,image/webp" aria-label="Flyer file" className="crm-input text-[12px]" required />
          </ActionForm>
        </div>
      </div>

      <Modal
        open={confirmApply !== null}
        kicker="Please confirm"
        title="Use this flyer?"
        confirmLabel="Use this flyer"
        tone="warn"
        onCancel={() => setConfirmApply(null)}
        onConfirm={() => {
          const p = confirmApply;
          setConfirmApply(null);
          if (p) applyPending(p);
        }}
      >
        This event already has a flyer. Using this one replaces it (the old file stays in storage; the event just stops using it).
      </Modal>
    </Card>
  );
}
