#!/usr/bin/env node
// Generate Supabase-style TypeScript types for the `app` schema straight from
// the Postgres catalog (no Docker needed). Output matches the shape produced by
// `supabase gen types typescript`, so supabase-js clients type-check the same.
//
//   DATABASE_URL=postgres://... node supabase/scripts/gen-types.mjs > src/lib/database.types.ts
import { execFileSync } from "node:child_process";

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("DATABASE_URL is required");
  process.exit(1);
}
const SCHEMA = process.env.SCHEMA || "app";

const sql = `
with cols as (
  select c.relname as table_name, c.relkind, a.attname as column_name, a.attnum,
         format_type(a.atttypid, a.atttypmod) as data_type,
         t.typname, t.typtype, et.typname as elem_typname, et.typtype as elem_typtype,
         not a.attnotnull as nullable,
         (a.atthasdef or a.attidentity <> '' or a.attgenerated <> '') as has_default
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  join pg_type t on t.oid = a.atttypid
  left join pg_type et on et.oid = t.typelem and t.typcategory = 'A'
  where n.nspname = '${SCHEMA}' and c.relkind in ('r','v') and a.attnum > 0 and not a.attisdropped
),
enums as (
  select t.typname, array_agg(e.enumlabel order by e.enumsortorder) as labels
  from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = '${SCHEMA}' group by t.typname
),
fns as (
  select p.proname, p.proretset,
         coalesce(p.proargnames, '{}') as argnames,
         coalesce(p.proargmodes::text[], '{}') as argmodes,
         (select array_agg(format_type(x, null)) from unnest(coalesce(p.proallargtypes, p.proargtypes::oid[])) x) as argtypes,
         p.pronargdefaults, p.pronargs,
         format_type(p.prorettype, null) as rettype, rt.typtype as rettyptype
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace join pg_type rt on rt.oid = p.prorettype
  where n.nspname = '${SCHEMA}' and p.prokind = 'f'
    and rt.typname <> 'trigger' and p.proname not like '\\_%'
    and has_function_privilege('authenticated', p.oid, 'execute')
)
select json_build_object(
  'cols', (select json_agg(cols order by table_name, attnum) from cols),
  'enums', (select json_agg(enums order by typname) from enums),
  'fns', (select json_agg(fns order by proname) from fns)
)`;

const raw = execFileSync("psql", [url, "-AtX", "-c", sql], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
const { cols = [], enums = [], fns = [] } = JSON.parse(raw);
const enumNames = new Set(enums.map((e) => e.typname));

function tsScalar(pgType) {
  const t = pgType.replace(/\(.*\)/, "").replace(/^app\./, "").trim();
  if (enumNames.has(t)) return `Database["${SCHEMA}"]["Enums"]["${t}"]`;
  if (/^(smallint|integer|bigint|numeric|real|double precision)$/.test(t)) return "number";
  if (t === "boolean") return "boolean";
  if (/^jsonb?$/.test(t)) return "Json";
  if (t === "void") return "undefined";
  if (t === "record") return "Json";
  return "string"; // uuid, text, citext, date, timestamptz, time, inet, ranges, bytea
}
function tsType(pgType) {
  if (pgType.endsWith("[]")) return `${tsScalar(pgType.slice(0, -2))}[]`;
  return tsScalar(pgType);
}

const tables = new Map();
const views = new Map();
for (const c of cols) {
  const target = c.relkind === "v" ? views : tables;
  if (!target.has(c.table_name)) target.set(c.table_name, []);
  target.get(c.table_name).push(c);
}

const ind = (n) => " ".repeat(n);
const key = (k) => (/^[a-z_][a-z0-9_]*$/.test(k) ? k : JSON.stringify(k));
let out = [];
out.push(`// Generated by supabase/scripts/gen-types.mjs — do not edit by hand.`);
out.push(`// Regenerate after every migration (see connect-crm/docs/ARCHITECTURE.md).`);
out.push(`export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];`);
out.push(``);
out.push(`export type Database = {`);
out.push(`  ${SCHEMA}: {`);
out.push(`    Tables: {`);
for (const [name, cs] of [...tables].sort(([a], [b]) => a.localeCompare(b))) {
  out.push(`${ind(6)}${key(name)}: {`);
  out.push(`${ind(8)}Row: {`);
  for (const c of cs) out.push(`${ind(10)}${key(c.column_name)}: ${tsType(c.data_type)}${c.nullable ? " | null" : ""};`);
  out.push(`${ind(8)}};`);
  out.push(`${ind(8)}Insert: {`);
  for (const c of cs) {
    const opt = c.nullable || c.has_default;
    out.push(`${ind(10)}${key(c.column_name)}${opt ? "?" : ""}: ${tsType(c.data_type)}${c.nullable ? " | null" : ""};`);
  }
  out.push(`${ind(8)}};`);
  out.push(`${ind(8)}Update: {`);
  for (const c of cs) out.push(`${ind(10)}${key(c.column_name)}?: ${tsType(c.data_type)}${c.nullable ? " | null" : ""};`);
  out.push(`${ind(8)}};`);
  out.push(`${ind(8)}Relationships: [];`);
  out.push(`${ind(6)}};`);
}
out.push(`    };`);
out.push(`    Views: {`);
for (const [name, cs] of views) {
  out.push(`${ind(6)}${key(name)}: {`);
  out.push(`${ind(8)}Row: {`);
  for (const c of cs) out.push(`${ind(10)}${key(c.column_name)}: ${tsType(c.data_type)} | null;`);
  out.push(`${ind(8)}};`);
  out.push(`${ind(8)}Relationships: [];`);
  out.push(`${ind(6)}};`);
}
out.push(`    };`);
out.push(`    Functions: {`);
const seen = new Set();
for (const f of fns) {
  if (seen.has(f.proname)) continue; // overloads: first wins (none today)
  seen.add(f.proname);
  const modes = f.argmodes.length ? f.argmodes : Array(f.argtypes?.length || 0).fill("i");
  const args = [];
  const outs = [];
  (f.argtypes || []).forEach((t, i) => {
    const m = modes[i] || "i";
    const name = f.argnames[i] || `arg${i}`;
    if (m === "i" || m === "b") args.push({ name, t });
    if (m === "o" || m === "t" || m === "b") outs.push({ name, t });
  });
  const firstDefault = f.pronargs - f.pronargdefaults;
  out.push(`${ind(6)}${key(f.proname)}: {`);
  if (args.length === 0) out.push(`${ind(8)}Args: Record<PropertyKey, never>;`);
  else {
    out.push(`${ind(8)}Args: {`);
    args.forEach((a, i) => out.push(`${ind(10)}${key(a.name)}${i >= firstDefault ? "?" : ""}: ${tsType(a.t)};`));
    out.push(`${ind(8)}};`);
  }
  let ret;
  if (outs.length) {
    ret = `{ ${outs.map((o) => `${key(o.name)}: ${tsType(o.t)}`).join("; ")} }`;
    ret = f.proretset ? `${ret}[]` : ret;
  } else {
    ret = tsType(f.rettype);
    if (f.proretset) ret = `${ret}[]`;
  }
  out.push(`${ind(8)}Returns: ${ret};`);
  out.push(`${ind(6)}};`);
}
out.push(`    };`);
out.push(`    Enums: {`);
for (const e of enums) out.push(`${ind(6)}${key(e.typname)}: ${e.labels.map((l) => JSON.stringify(l)).join(" | ")};`);
out.push(`    };`);
out.push(`    CompositeTypes: Record<PropertyKey, never>;`);
out.push(`  };`);
out.push(`};`);
out.push(``);
out.push(`type AppSchema = Database["${SCHEMA}"];`);
out.push(`export type Tables<T extends keyof AppSchema["Tables"]> = AppSchema["Tables"][T]["Row"];`);
out.push(`export type TablesInsert<T extends keyof AppSchema["Tables"]> = AppSchema["Tables"][T]["Insert"];`);
out.push(`export type TablesUpdate<T extends keyof AppSchema["Tables"]> = AppSchema["Tables"][T]["Update"];`);
out.push(`export type Enums<T extends keyof AppSchema["Enums"]> = AppSchema["Enums"][T];`);
out.push(`export type Views<T extends keyof AppSchema["Views"]> = AppSchema["Views"][T]["Row"];`);
out.push(`export type Functions<T extends keyof AppSchema["Functions"]> = AppSchema["Functions"][T];`);
process.stdout.write(out.join("\n") + "\n");
