import type { Metadata } from "next";
import Link from "next/link";

import { Alert, Card, EmptyState, NoAccess, PageHeader, Pagination, QueryError, TableWrap, buttonClass } from "@/components/ui";
import { householdsById, userNames } from "@/lib/data/lookups";
import { formatDateTime, todayInTz } from "@/lib/dates";
import { canAccess } from "@/lib/permissions";
import { hrefWith, pageParam, param, type RawSearchParams } from "@/lib/search-params";
import { getSession } from "@/lib/session";

export const metadata: Metadata = { title: "Statements" };

const PAGE_SIZE = 50;
const KIND_LABEL: Record<string, string> = { tax_year: "Tax-year statement", pledge: "Pledge statement", donation: "Donation receipt", event: "Event statement" };

export default async function StatementsPage({ searchParams }: { searchParams: Promise<RawSearchParams> }) {
  const session = await getSession();
  const header = <PageHeader title="Statements" description="Year-end tax statements, pledge statements and donation receipts issued to households." />;
  if (!canAccess(session, "statements")) {
    return (
      <>
        {header}
        <NoAccess area="Statements" access="statements" />
      </>
    );
  }
  const sp = await searchParams;
  const { db, center } = session;
  const tz = center.time_zone;
  const currentYear = Number(todayInTz(tz).slice(0, 4));
  const yearParam = Number(param(sp, "year"));
  const year = Number.isInteger(yearParam) && yearParam > 1990 ? yearParam : null;
  const kind = param(sp, "kind");
  const page = pageParam(sp);

  let q = db
    .from("statements")
    .select("id, household_id, kind, tax_year, storage_path, generated_at, generated_by", { count: "exact" })
    .eq("center_id", center.id);
  if (year) q = q.eq("tax_year", year);
  if (kind && kind in KIND_LABEL) q = q.eq("kind", kind);
  const from = (page - 1) * PAGE_SIZE;
  const res = await q.order("generated_at", { ascending: false }).range(from, from + PAGE_SIZE - 1);
  const rows = res.data ?? [];
  const [households, generators] = await Promise.all([
    householdsById(db, rows.map((r) => r.household_id)),
    userNames(db, center.id, rows.map((r) => r.generated_by)),
  ]);

  return (
    <>
      {header}
      <div className="mb-4">
        <Alert tone="info">
          Statements are generated by the statements service (a Supabase edge function) and stored as files; this page lists what has been
          issued. Generating a new batch is not available from the console yet.
        </Alert>
      </div>
      <form method="get" action="/giving/statements" className="mb-4 flex flex-wrap items-end gap-3">
        <div>
          <label htmlFor="year" className="crm-label">
            Tax year
          </label>
          <select id="year" name="year" defaultValue={year ? String(year) : ""} className="crm-input min-w-32">
            <option value="">All years</option>
            {Array.from({ length: 8 }, (_, i) => currentYear - i).map((y) => (
              <option key={y} value={y}>
                {y}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label htmlFor="kind" className="crm-label">
            Kind
          </label>
          <select id="kind" name="kind" defaultValue={kind ?? ""} className="crm-input min-w-52">
            <option value="">All kinds</option>
            {Object.entries(KIND_LABEL).map(([k, v]) => (
              <option key={k} value={k}>
                {v}
              </option>
            ))}
          </select>
        </div>
        <button type="submit" className={buttonClass("primary")}>
          Apply
        </button>
      </form>
      {res.error ? (
        <QueryError what="statements" error={res.error} retryHref={hrefWith("/giving/statements", sp, {})} />
      ) : (
        <Card padded={false}>
          {rows.length === 0 ? (
            <EmptyState title="No statements issued yet" />
          ) : (
            <TableWrap>
              <table className="crm-table">
                <thead>
                  <tr>
                    <th>Household</th>
                    <th>Kind</th>
                    <th>Tax year</th>
                    <th>Generated</th>
                    <th>File</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((s) => {
                    const h = households.map.get(s.household_id);
                    return (
                      <tr key={s.id}>
                        <td>
                          <Link href={`/households/${s.household_id}`} className="crm-link">
                            {h?.display_name ?? "Household"}
                          </Link>
                          <div className="font-mono text-xs text-muted">{h?.household_number ?? ""}</div>
                        </td>
                        <td>{KIND_LABEL[s.kind] ?? s.kind}</td>
                        <td>{s.tax_year ?? "—"}</td>
                        <td>
                          {formatDateTime(s.generated_at, tz)}
                          <div className="text-xs text-muted">{s.generated_by ? (generators.get(s.generated_by)?.name ?? "staff") : "automatic"}</div>
                        </td>
                        <td className="font-mono text-xs">{s.storage_path ?? <span className="font-sans text-muted">Not stored</span>}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </TableWrap>
          )}
          <Pagination page={page} pageSize={PAGE_SIZE} total={res.count ?? null} hrefFor={(n) => hrefWith("/giving/statements", sp, { page: n })} />
        </Card>
      )}
    </>
  );
}
