-- Wave E integration.
--
-- The import allow-list (app.import_entities) is generated from src/lib/import/registry.ts.
-- e-money (0413: written-off pledges, opening balances) and e-people-legal (0423: date of
-- death) each re-seeded it from their own copy of the registry; 0423 runs last and would drop
-- e-money's additions. Re-seed once more from the merged registry.
set client_min_messages = warning;

-- BEGIN import_entities seed (generated from src/lib/import/registry.ts)
insert into app.import_entities (key, label, tier, sort, target_table, write_perms, module_key, columns, extras, natural_key, money_columns, has_center) values
  ('zones', 'Zones and ZIP codes', 'setup', 30, 'zones', array['settings.manage'], 'people',
   array['name','zip_codes'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('inboxes', 'Inboxes', 'setup', 31, 'inboxes', array['settings.manage'], 'comms',
   array['key','name','response_target_hours'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('bank_accounts', 'Bank accounts', 'setup', 32, 'bank_accounts', array['accounting.manage'], 'giving',
   array['active','institution','last4','name','statement_format'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('funds', 'Funds', 'setup', 33, 'funds', array['giving.manage'], 'giving',
   array['active','key','name','qbo_class_id','restricted'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('membership_types', 'Membership types', 'setup', 34, 'membership_types', array['settings.manage'], 'membership',
   array['active','ec_approval_required','fee_cents','includes_spouse','key','name','period_months','reference_required','tier','voting_wait_days'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('store_categories', 'Store categories', 'setup', 35, 'store_categories', array['store.manage'], 'store',
   array['name','sort_order'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('calendar_layers', 'Calendar layers', 'setup', 36, 'calendar_layers', array['content.manage'], 'calendar',
   array['color','default_on','key','kind','name','source_url'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('pathshala_tracks', 'Pathshala tracks', 'setup', 37, 'pathshala_tracks', array['pathshala.manage'], 'pathshala',
   array['key','name'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('pathshala_terms', 'Pathshala terms', 'setup', 38, 'pathshala_terms', array['pathshala.manage'], 'pathshala',
   array['ends_on','fee_per_child_cents','fee_per_family_cap_cents','membership_required','name','registration_closes_at','registration_opens_at','sibling_discount_pct','starts_on','status'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('practices', 'Practices (My Jain Way)', 'setup', 39, 'practices', array['content.manage'], 'jain_way',
   array['active','category','default_minutes','description','key','name','points','sort_order'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('gyan_goals', 'Gyan Path goals', 'setup', 40, 'gyan_goals', array['content.manage'], 'gyan_path',
   array['description','key','name','recommended','sort_order'],
   '{}'::text[], array['key'], '{}'::text[], true),
  ('campaigns', 'Campaigns', 'setup', 50, 'campaigns', array['giving.manage'], 'giving',
   array['description','ends_on','fund_id','goal_cents','kind','name','starts_on','status'],
   '{}'::text[], array['name'], array['goal_cents'], true),
  ('event_templates', 'Event templates', 'setup', 51, 'event_templates', array['events.manage'], 'events',
   array['description','name'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('event_template_items', 'Event template checklist items', 'setup', 52, 'event_template_items', array['events.manage'], 'events',
   array['name','offset_days','phase','priority','sort_order','template_id'],
   '{}'::text[], array['template_id','name'], '{}'::text[], true),
  ('volunteer_groups', 'Volunteer groups', 'setup', 53, 'volunteer_groups', array['volunteers.manage'], 'volunteers',
   array['name','requires_background_check','requires_waiver_kind'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('pathshala_levels', 'Pathshala levels', 'setup', 54, 'pathshala_levels', array['pathshala.manage'], 'pathshala',
   array['key','max_age','min_age','name','sort_order','track_id'],
   '{}'::text[], array['track_id','key'], '{}'::text[], true),
  ('gyan_levels', 'Gyan Path levels', 'setup', 55, 'gyan_levels', array['content.manage'], 'gyan_path',
   array['chapter','goal_id','key','name','points','requires_teacher_signoff','sort_order'],
   '{}'::text[], array['goal_id','key'], '{}'::text[], false),
  ('gyan_steps', 'Gyan Path steps', 'setup', 60, 'gyan_steps', array['content.manage'], 'gyan_path',
   array['kind','level_id','points','sort_order','title'],
   '{}'::text[], array['level_id','title'], '{}'::text[], false),
  ('opportunities', 'Opportunities and sponsorships', 'setup', 70, 'opportunities', array['giving.manage'], 'giving',
   array['amount_cents','campaign_id','description','kind','min_amount_cents','name','quantity_available','sort_order','status'],
   '{}'::text[], array['campaign_id','name'], array['amount_cents'], true),
  ('labh_options', 'Labh options', 'setup', 71, 'labh_options', array['giving.manage'], 'giving',
   array['active','amount_cents','campaign_id','fund_id','name','sort_order'],
   '{}'::text[], array['name'], array['amount_cents'], true),
  ('pickup_windows', 'Store pickup windows', 'setup', 72, 'pickup_windows', array['store.manage'], 'store',
   array['capacity','ends_at','location','order_cutoff_at','starts_at'],
   '{}'::text[], array['starts_at'], '{}'::text[], true),
  ('pathshala_classes', 'Pathshala classes', 'setup', 73, 'pathshala_classes', array['pathshala.manage'], 'pathshala',
   array['capacity','ends_time','level_id','meets_on','name','room','starts_time','term_id'],
   '{}'::text[], array['term_id','name'], '{}'::text[], true),
  ('whatsapp_groups', 'WhatsApp groups', 'setup', 74, 'whatsapp_groups', array['comms.send'], 'comms',
   array['active','audience','description','name','zone_id'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('households', 'Households', 'records', 100, 'households', array['people.manage'], 'people',
   array['address_line1','address_line2','city','directory_opt_in','display_name','household_number','notes','physical_mail_opt_in','postal_code','state_region','zone_id'],
   array['crm_id','legacy_id'], '{}'::text[], '{}'::text[], true),
  ('people', 'People', 'records', 101, 'people', array['people.manage'], 'people',
   array['date_of_birth','deceased_on','email','employer','first_name','gender','is_deceased','language','last_name','member_number','phone_e164','preferred_name','profession'],
   array['crm_id','email_opt_in','email_opt_in_date','email_opt_in_source','full_name','household_id','is_primary','legacy_id','other_emails','relationship'], '{}'::text[], '{}'::text[], true),
  ('household_members', 'Household members and relationships', 'records', 110, 'household_members', array['people.manage'], 'people',
   array['household_id','is_primary','joined_at','left_at','person_id','role'],
   '{}'::text[], '{}'::text[], '{}'::text[], true),
  ('external_ids', 'Identifiers', 'records', 111, 'external_ids', array['people.manage','giving.manage'], 'people',
   array['household_id','kind','label','person_id','system','value'],
   '{}'::text[], '{}'::text[], '{}'::text[], true),
  ('channel_optins', 'Consents, opt-ins and opt-outs', 'records', 112, 'channel_optins', array['comms.send'], 'comms',
   array['address','channel','opted_in','person_id','recorded_at','source'],
   '{}'::text[], '{}'::text[], '{}'::text[], true),
  ('special_days', 'Special days', 'records', 120, 'special_days', array['people.manage'], 'people',
   array['calendar_date','household_id','kind','label','person_id','tithi','tithi_month'],
   '{}'::text[], '{}'::text[], '{}'::text[], true),
  ('memberships', 'Memberships (current and past)', 'records', 121, 'memberships', array['people.manage'], 'membership',
   array['crm_external_id','ends_on','household_id','membership_type_id','notes','person_id','starts_on','status'],
   '{}'::text[], '{}'::text[], '{}'::text[], true),
  ('pathshala_enrollments', 'Pathshala enrollments', 'records', 122, 'pathshala_enrollments', array['pathshala.manage'], 'pathshala',
   array['class_id','household_id','notes','status','student_person_id','term_id'],
   '{}'::text[], array['term_id','student_person_id'], '{}'::text[], true),
  ('pathshala_teachers', 'Pathshala teachers', 'records', 123, 'pathshala_teachers', array['pathshala.manage'], 'pathshala',
   array['class_id','person_id','role'],
   '{}'::text[], array['class_id','person_id'], '{}'::text[], true),
  ('volunteer_interests', 'Volunteer interests', 'records', 124, 'volunteer_interests', array['volunteers.manage'], 'volunteers',
   array['group_id','person_id','status'],
   '{}'::text[], array['person_id','group_id'], '{}'::text[], true),
  ('background_checks', 'Background checks', 'records', 125, 'background_checks', array['safety.manage'], 'volunteers',
   array['cleared_on','expires_on','person_id','provider','status'],
   '{}'::text[], '{}'::text[], '{}'::text[], true),
  ('store_items', 'Store items and opening stock', 'records', 130, 'store_items', array['store.manage'], 'store',
   array['category_id','description','low_stock_threshold','name','pack_size','price_cents','qbo_item_id','sku','status','taxable','track_inventory'],
   array['opening_stock'], array['sku'], array['price_cents'], true),
  ('pledges', 'Pledges', 'history', 200, 'pledges', array['giving.manage'], 'giving',
   array['amount_cents','anonymous','campaign_id','closed_at','crm_external_id','dedication','due_on','fund_id','household_id','pledge_number','pledged_at','pledged_by_person_id','source','status','write_off_reason','written_off_by_name'],
   array['paid_so_far'], '{}'::text[], array['amount_cents','paid_so_far'], true),
  ('payments', 'Payments (history)', 'history', 210, 'payments', array['giving.manage'], 'giving',
   array['amount_cents','check_number','crm_external_id','household_id','memo','method','payer_person_id','provider_ref','receipt_number','received_on','status'],
   array['allocate_to','allocation_cents'], '{}'::text[], array['amount_cents'], true),
  ('payment_allocations', 'Payment allocations', 'history', 220, 'payment_allocations', array['giving.manage'], 'giving',
   array['amount_cents','payment_id','pledge_id'],
   '{}'::text[], array['payment_id','pledge_id'], array['amount_cents'], true),
  ('recurring_gifts', 'Recurring gifts', 'history', 230, 'recurring_gifts', array['giving.manage'], 'giving',
   array['amount_cents','campaign_id','frequency','fund_id','household_id','method','next_charge_on','person_id','starts_on'],
   array['legacy_id'], '{}'::text[], array['amount_cents'], true),
  ('bolis', 'Past bolis', 'history', 240, 'bolis', array['bolis.manage'], 'bolis',
   array['campaign_id','closes_at','event_id','kind','name'],
   '{}'::text[], array['name'], '{}'::text[], true),
  ('boli_entries', 'Boli results', 'history', 241, 'boli_entries', array['bolis.manage'], 'bolis',
   array['amount_cents','boli_id','display_name','entered_at','household_id','person_id'],
   array['legacy_id'], '{}'::text[], array['amount_cents'], true),
  ('events', 'Past events', 'history', 242, 'events', array['events.manage'], 'events',
   array['description','ends_at','name','program_year','starts_at','venue'],
   array['legacy_id'], '{}'::text[], '{}'::text[], true),
  ('attendees', 'Event attendance', 'history', 243, 'attendees', array['events.manage'], 'events',
   array['checked_in_at','event_id','person_id'],
   array['household_id'], '{}'::text[], '{}'::text[], true),
  ('pathshala_attendance', 'Pathshala attendance', 'history', 244, 'pathshala_attendance', array['pathshala.manage'], 'pathshala',
   array['note','status'],
   array['class_id','held_on','student_person_id'], '{}'::text[], '{}'::text[], true)
on conflict (key) do update set label = excluded.label, tier = excluded.tier, sort = excluded.sort, target_table = excluded.target_table,
  write_perms = excluded.write_perms, module_key = excluded.module_key, columns = excluded.columns, extras = excluded.extras,
  natural_key = excluded.natural_key, money_columns = excluded.money_columns, has_center = excluded.has_center;
-- END import_entities seed
